### ISSUE TITLE
Implement a validation so end date cannot be earlier than start date

### ISSUE THREAD

**Issue by mdevare** [AGROFIMS/hagrofims#10]
end date cannot be earlier than start date - need to include validation for this

**Comment by ivanperezm** [comment]
This module is already implemented in the development version.

**Comment by celineaubert** [comment]
It doesn't seem to work in the V23. I can enter an end date earlier than the start date

![image](https://user-images.githubusercontent.com/14092820/57691877-9f5cf080-7645-11e9-9e99-12b19515bf2b.png)


![image](https://user-images.githubusercontent.com/14092820/57691841-8e13e400-7645-11e9-9a6b-1e1b62212c58.png)
