### ISSUE TITLE
Dates for experimental conditions set on expriment start date

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#11]
Have blank text boxes for dates. Once you click on the start date to enter it, the calender should points the start date of the experiment.
Once the start date of the experimental condition is selected, the end date is automatically selected to be the same (since most of the experiment conditons are done in one day)

**Comment by ivanperezm** [comment]
This module is already implemented in the development version.

**Comment by celineaubert** [comment]
It does not seems to work on the version 21. 
- Some dates have blank text boxes, others are filled with the date of today. 
- The start date of an experimental condition is never the start date of the experiment
- End date of an experimental condition is not automatically selected after selecting the start date

**Comment by marieALaporte** [comment]
Dates are blank by default. 
Validation for the end date still needs to be implemented
