### ISSUE TITLE
Duplicate weeding information

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#132]
Duplicate the information of the weeding number 1 to the other weeding numbers.

Change ''weeding number 1'' to '' weeding #1'' to be consistent with irrigation.

**Comment by celineaubert** [comment]
Paris WS comments on Crop Phenology:
- Fruit development could be contextualized according to the crop you entered in the beginning.
- Is the crop phenology at all linked to the crops you’re interested in?  And if you have more than one crop, can you have multiple different crop phenologies?
- Add more than one “other” phenological stage. 
- Inconsistency between growth stages.  50% X date available, but not also 50% Y date.

**Comment by vhualla** [comment]
![image](https://user-images.githubusercontent.com/13644354/48561010-109d3000-e8bd-11e8-8871-be67b4ea3d3f.png)

**Comment by marieALaporte** [comment]
there is no weeding number anymore. Just use the add weeding button to add an instance of weeding. 
Will not duplicate the information entered but this is not a needed feature I think.
@celineaubert If fine with you, close the issue
