### ISSUE TITLE
clone a given factor 

### ISSUE THREAD

**Issue by marieALaporte** [AGROFIMS/hagrofims#14]
particularly in the non full factorial part

ideally, users should be able to say "replicate x times"

**Comment by omarbenites** [comment]
I close this issues because it duplicated in #142.

**Comment by celineaubert** [comment]
Levels and notes are not duplicated

![image](https://user-images.githubusercontent.com/14092820/56743132-4a306c00-6776-11e9-8c64-1c6f4e393aae.png)

**Comment by celineaubert** [comment]
This issue is not relevant anymore for the new interface for Factor.
