### ISSUE TITLE
Improve Factor/Design module

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#142]
I have tried to resolved different issues related to the Factor module (#138 #131 #130 #126 #95 #41 #28  #15 #14). I have made changes directly in the Excelsheet used by the CIP team, and a mock-up.

Modifications made in the attached Excel sheet : [FACTOR_V6- Celine modification 25-10-2018.xlsx](https://github.com/AGROFIMS/hagrofims/files/2515579/FACTOR_V6-.Celine.modification.25-10-2018.xlsx)
-	Suppression of the sub-groups when not necessary (#138) (#130)
-	Factors displayed in the same order that the experimental conditions are done in the field
-	Tried to keep the lists consistent (always start with start date, end date)
-	Used only the spelling ‘’implement type’’ to harmonize the list
-	Separated mulch and residue management
-	Separated Direct seeding and transplanting
-	Added: species as factor (#95)
- Limit the species to the crop added in the crop module  (#126)
- Added distance between bunds (#131) in direct seeding and transplanting
-	Added ‘’other’’ in each list (#41)
-	Added irrigation amount

Modification proposed in the mock-up:
- one note box for each factor #130 
- Add of a button ''add a factor''  #15 
- Add of a button ''duplicate'' #14
- Add of a button ''remove''
- Delete the box '' number of factor'' #28 
- design suggestion: select box appears only when the precedent select box is filled, since a third select box is not always needed. 
![image](https://user-images.githubusercontent.com/14092820/47510372-52b3f280-d878-11e8-855e-9465bd927c38.png)

**Comment by mdevare** [comment]
Hi Celine,

Can we meet for the afternoon of Wednesday, assuming that a couple of other mtgs don’t get scheduled (as I indicated availability but haven’t heard back)? Perhaps from 14:00 to about 17:00 — in my office (in Agropolis). If that works, send a calendar invite, please? We can systematically look through the issues and figure out what’s done, what I need to prioritize etc.

Thanks,
Medha

Sent from my iPhone

On 25 Oct 2018, at 11:22, Céline Aubert <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #142<https://github.com/AGROFIMS/hagrofims/issues/142> to @mdevare<https://github.com/mdevare>.

**Comment by celineaubert** [comment]
done
