### ISSUE TITLE
Make available mapping between data dictionary items and the labels that appear as actual column headings in downloaded fieldbook

### ISSUE THREAD

**Issue by brianjlowe** [AGROFIMS/hagrofims#148]
Medha, Marie and I were discussing remaining requirements for the AgroFIMS RDF converter and decided that this is a pretty critical issue.  

The rows in the AgroFIMS Agronomy Data Dictionary spreadsheed that drives the elements available in the HIDAP AgroFIMS application will be supplemented with up to four additional columns containing URIs that specify how the corresponding item will be mapped to RDF.

When the user downloads a fieldbook spreadsheet, any column or row headings (which the user must not change) need to be traceable back to the original items from the supplied data dictionary spreadsheet.  

We imagined that the most logical way of handling this might be to have a processed version of the data dictionary tables that can be downloaded from the HIDAP AgroFIMS server that includes, for each item, the label as it appears in the user's fieldbook -- after any processing of the label string.

**Comment by celineaubert** [comment]
@marieALaporte

**Comment by celineaubert** [comment]
issue not applicable anymore with the Angular version
