### ISSUE TITLE
UI/UX Discussion - Dropdown Ranges

### ISSUE THREAD

**Issue by frostbytten** [AGROFIMS/hagrofims#15]
We should have a discussion or sample implementation where we have an **+ Add New** and **duplicate** button any place a ranged number field is being used. Examples of this would be adding factors, adding management practices (irrigation, soil fertility, etc) and items like this. This feature would also help enable the copying of information between entries where only a slight modification is being made.

**Comment by marieALaporte** [comment]
fixed in v22
