### ISSUE TITLE
Add third factor for split plot design

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#154]

**Comment by reyzaguirre** [comment]
this is done in st4gi

**Comment by celineaubert** [comment]
Hi @reyzaguirre,
could you please explain a bit what you did for this issue, and what remain to be done to integrate it to AgroFIMS? Also, would you have an example of a survey design with a third factor for split plot?
Many thanks!

@mdevare

**Comment by reyzaguirre** [comment]
Hi @celineaubert 
Function https://github.com/reyzaguirre/st4gi/blob/master/R/cr_spld.R creates this randomization up to 3 factors. Following split plot idea, it is:
- first factor randomized in complete blocks.
- second factor randomized inside each first factor level (so each first factor level is a complete block for second factor)
- third factor, if any, randomized inside each second factor level (so each second factor level is a complete block for third factor)
I do not have a real example of this with 3 factors, but you can get an example of randomization with 3 factors with this code:

library(st4gi)
A <- paste0("a", 1:2) # two levels for first factor
B <- paste0("b", 1:4) # four levels for second factor
C <- paste0("c", 1:3) # three levels for third factor
cr.spld(c("A", "B", "C"), list(A, B, C), 3) # last 3 is for 3 full blocks
About implementation in AGROFIMS we must ask @omarbenites
