### ISSUE TITLE
Create a fieldbook ID and a more generic experiment ID

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#156]
Create a fieldbook ID (exactly the same the the current experiment ID) in the crop tab, add a column in ''manage fieldbook'' for the fieldbook ID, 

Make the current experiment ID more generic (First 2 letters of experiment name + First 2 letters of experiment + timestamp)

**Comment by reyzaguirre** [comment]
In R we can use for the experiment ID something like:
paste0(substring("PROJECTNAME", 1, 2), substring("PROJECTCENTER", 1, 2), round(as.numeric(Sys.time())))
