### ISSUE TITLE
Remove Variable id or VariableId in Weather Sheet

### ISSUE THREAD

**Issue by omarbenites** [AGROFIMS/hagrofims#159]
Remove `Variable id` or `VariableId` in Weather Sheet `(Weather station)`

https://docs.google.com/spreadsheets/d/1XNPUSoRFkUTDGU4BzPDGVKTVIRIz8ddrmkfb28XMQ9I/edit#gid=1860889663

![image](https://user-images.githubusercontent.com/5264796/52390148-e050d200-2a64-11e9-82a6-571605921d26.png)

**Comment by celineaubert** [comment]
done
