### ISSUE TITLE
Change title Crop measurement to crop phenology

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#162]
Change title Crop measurement to crop phenology in the Phenology module

![image](https://user-images.githubusercontent.com/14092820/52437208-55172100-2ae4-11e9-8560-e939c11e32c0.png)

**Comment by vhualla** [comment]
![image](https://user-images.githubusercontent.com/13644354/52591813-d0454380-2e12-11e9-9f95-c7c07b6d1d75.png)
