### ISSUE TITLE
Some information from the Harvest module is missing in the Fieldbook

### ISSUE THREAD

**Issue by marieALaporte** [AGROFIMS/hagrofims#164]
Some field from the Harvest module are not exported to the Fieldbook. cf. screenshot

<img width="1110" alt="capture d ecran 2019-02-07 a 15 08 20" src="https://user-images.githubusercontent.com/5664149/52439840-8abf0880-2aea-11e9-8af7-97bb9d5ba381.png">

**Comment by omarbenites** [comment]
Now it is fixed.
