### ISSUE TITLE
Download enhacements

### ISSUE THREAD

**Issue by omarbenites** [AGROFIMS/hagrofims#166]
[NOW FIXED! 👍 ]
1. Se va exportar un sheet llamado Trait List donde

- Los labels del field operations deben estar acompañados de: `Group`, `Subgroup`, ... `Label` 

2. Los trait con unidades deben ser exportado como
Ex.
`harvest_cm`
 12

**Comment by omarbenites** [comment]
@marieALaporte here you can attach the file

**Comment by omarbenites** [comment]
Fix issues in metadata as follow
- experimental unit
- factor label name
- inclide expeirmwntal design and parameters
![screenshot_2019-02-19-10-32-39](https://user-images.githubusercontent.com/5264796/53065054-13995500-3498-11e9-8221-386a4d1665a7.png)
![screenshot_2019-02-19-10-32-28](https://user-images.githubusercontent.com/5264796/53065055-13995500-3498-11e9-9dca-45278fb1f735.png)

**Comment by omarbenites** [comment]
[ ]   Seedbed preparation: list only the variables for the method chosen in AgroFIMS. I have selected tillage in AgroFIMS, but I also get the variables for  ''puddling'', and ''land levelling'' in the fieldbook.
[ ]   Planting-transplanting: list only the variables for the method selected in AgroFIMS. I have selected ''direct seeding'' but I also get the variables for ''transplanting''
[ ]   Trait list : This is what I get:

 
![image](https://user-images.githubusercontent.com/5264796/53438300-9d33b000-39cd-11e9-8f37-40a0e6c1961d.png)

[ ]	Phenology: should be like ''Fieldbook'' with PLOT, ROW, COL, TREATMENT, and the variables selected      
![image](https://user-images.githubusercontent.com/5264796/53438365-bdfc0580-39cd-11e9-916e-fb4ccb48c374.png)

[ ]	Weather and Soil : the column header should be the variables name, without PLOT, ROW, COL, TREATMENT.   
![image](https://user-images.githubusercontent.com/5264796/53438393-cbb18b00-39cd-11e9-8a91-5ce393fa2883.png)

[ ]	What is ''Input''?

This is how is should be:

**Comment by omarbenites** [comment]
- [x] Intecrop fails with soil and fertitlity (solved 👍 )
![image](https://user-images.githubusercontent.com/5264796/53919978-9a723400-4039-11e9-81ac-f9e850e009e4.png)

**Comment by omarbenites** [comment]
- [ ] **KDSMART RULES**

We had a call with Brian and Medha this morning about the ''NumberofMeasurementperPlot''. In KDSmart, they add a # in the trait name to give the number of measurement per plot. I put an example in the attached file with 2 variables in yellow in the Trait List and in the Fieldbook tab. 

HEADER RULE IN FIELDBOOK: ``TraitName__(NumberMeaPerSeason)#(NumberMeaPerPlot)``


If Number of Measurement per season = 2
and Number of measurement per plot = 3

The Trait name in the fieldbook will be:
TraitName__1#1, TraiName__1#2, TraitName__1#3, TraitName__2#1, TraitName__2#2, TraitName__2#3

Therefore, we don't need to create a ''subsample'' column.

**Comment by omarbenites** [comment]
METADATA
- Treatment: should use the traitName label - should not be called ''Technique'' but ''tillage_technique''

Residue management tab
- [x] Residue_management_residue_incorporation_depthcm - should be Residue_management_residue_incorporation_depth_cm
- [x] Residue_management_description_start date - should be Residue_management_description_start_date
The names are correct tin the Datadictionnary

Irrigation tab
- [x] only 1 underscore instead of the 2 required by KDSmart: Irrigation_splinkler_irrigation_system_1 should be Irrigation_splinkler_irrigation_system__1

Harvest tab
- [ ] why is there a « __1 » when there is only one Harvest process? Whereas the is no « __1 » in the residue management tab, for which there is only one process too. Make it consistent.

- [x] In AgroFIMS I entered ''Harvest cut height''= 15cm, in the fieldbook the 15 is under Harvest_amount 

TraitList
- [ ] There are more variables in the TraitList than in the process tabs: Weeding_end_date and residue management_end_date for instance

**Comment by omarbenites** [comment]
Celine reported:

- [ ] checked the Excel file and it seems that they are still some little bugs:


- [ ] Funding Agency name: name of the CGIAR center is missing. I enterted Bioversity International in AgroFIMS : 


- [ ] Experiment lead: I entered nothing in AgroFIMS, but it automatically selected CGIAR center in the fieldbook. 

- [ ] Factor: I have 5 factors in my experiment. Why is there only 3 of them in a single column in the fieldbook? 


- [ ] Crop: Other I have an ''Other'' crop. In AgroFIMS, the crop measurement tab didn't appear for ''other''. In the fieldbook, the measurements selected for Maize appear also in the tab for Other 

- [x] Name of weather variable: should use TraitName
- [x] Name of soil variable in labbook: should use TraitName

- [ ] Variables: 
not the same name used in TraitList and in the tab. Ex: in Traitlist: Soil_fertility_Product_rate , in Soil fertility tab: Soil_fertility_product_rate_(kg/ha)__1
more variables in the TraitList than in the Soil fertility tab. I didn't find the names of the variables in the red square in the DataDictionnary in the Drive. Please use the names listed in the TraitName colunm. 
the variables without a VariableiD should not appear in the fieldbook (ex: Soil_fertility_biofertilizer_other)

- [ ] Direct seeding variables are in the trait list, but there is no ''Direct seeding'' tab. Plus I only selected - - [ ] Direct seeding and there are also variables for Transplanting.

**Comment by celineaubert** [comment]
- [ ] In the TraitList, add name of the Crop in the ''Crop'' column for phenology. 
- [ ] For intercrop, concatenate the name of the crop with the name of the variable for Phenology, planting and harvest. ex'' cassava_harvest_start_date

**Comment by celineaubert** [comment]
Better if the cells that have not been fill in AgroFIMS are blank. Don't add ''NA''
![image](https://user-images.githubusercontent.com/14092820/54238237-360f1300-4518-11e9-8fe6-a610e6af5342.png)

**Comment by celineaubert** [comment]
In the Excel fielbook, there is a mix between the factor -levels.

This is what I get:
![image](https://user-images.githubusercontent.com/14092820/54238412-ba619600-4518-11e9-936d-561eb710957c.png)

It should be like this:
![image](https://user-images.githubusercontent.com/14092820/54238437-c8171b80-4518-11e9-9f02-ee53b7a284b7.png)

**Comment by celineaubert** [comment]
If the NumberofMeasurmentperPlot is 1, the name of the trait in the tab headers should be TraitName__1 ,  no #1.

**Comment by celineaubert** [comment]
- [ ] In Metadata, ''Select crop 1'' , call it ''Crop 1'' (same for crop 2,3, ...)

- [ ] ''Crop variety(s) 1 '', call it ''Crop variety 1'' (same for variety 2,3, ...)

- [ ] In Metadata find a better way to link Crop and Crop variety. In the example it is not possible to know which variety is maize and which on is soybean
Example:
![image](https://user-images.githubusercontent.com/14092820/54622051-1c665200-4a69-11e9-92b1-5cf9c4d82223.png)

Possible solutions
 1. list the varieties under the Crop
![image](https://user-images.githubusercontent.com/14092820/54622311-a8787980-4a69-11e9-98ac-c52fdd94359c.png)

2. Add the name of the crop into the row header
![image](https://user-images.githubusercontent.com/14092820/54622617-2c326600-4a6a-11e9-920d-e93ab37d979a.png)
 3. any other solution you think off

**Comment by celineaubert** [comment]
- [ ] Downloaded fielbook metadata should have the AgroFIMS version - to help to find issues

**Comment by celineaubert** [comment]
- [ ] Name of the Fielbook file instead of fileNameBook: Fieldbook ID-System ID

**Comment by celineaubert** [comment]
- [ ] Have info about Person group per person number. All info about person 1 should be display together, all info about person 2 should be display together
**how it is currently (info mixed between person 1 and 2)**
![image](https://user-images.githubusercontent.com/14092820/59694694-57535f80-91e9-11e9-8f6e-bfde6cc0e6d5.png)

How it should be
![image](https://user-images.githubusercontent.com/14092820/59694871-92559300-91e9-11e9-9012-81df9098e3a0.png)

**Comment by celineaubert** [comment]
Have different Ids, trait names and trait alias when a measurement is used for 2 crops in the same expriment.

How it is currently in the Excel fieldbook
![image](https://user-images.githubusercontent.com/14092820/59697058-7a800e00-91ed-11e9-9cb6-68927dad82e3.png)

![image](https://user-images.githubusercontent.com/14092820/59697105-8ec40b00-91ed-11e9-942c-1a6897149f85.png)

**Comment by celineaubert** [comment]
Hi @omarbenites 

here is the last 
HEADER RULE IN FIELDBOOK: **(NumberMeaPerSeason):TraitName__(NumberMeaPerPlot)**
ex: 
NumberMeaPerSeason =2
NumberMeaPerPlot= 3

Header in fieldbook, in the Soil tab:
1:SoilPorosity__1, 1:SoilPorosity__2, 1:SoilPorosity__3, 2:SoilPorosity__1, 2:SoilPorosity__2, 2:SoilPorosity__3
[see Excel file](https://github.com/AGROFIMS/hagrofims/files/3492872/RCBD_full_factorial_without_._Mostly-Repaired.xlsx)




**Explanation for this choice from Brian**
**Naming of Traits using nMeasurementsPerSeason and nMeasurementsPerPlot.**

It is better to use the "nPerSeason" to specify the "prefix" and the "nPerPlot" for the TraitInstance suffix.
By doing it in this way it will be much easier for the user in KDSmart.
When KDSmart asks the user to select the "active" Traits, it presents each of the TraitInstances grouped within the Trait.
So by using the TraitInstance-number for the "nPerPlot" they will see the following for nPerSeason==3 and nPerPlot==2:

 .---- nPerSeason
 |
 v
( )  1:PH
   ( ) 1:PH__1  <--- nPerPlot
   ( ) 1:PH__2

(*)  2:PH       <--- One click selects all the "children"
   (*) 2:PH__1
   (*) 2:PH__2

( )  3:PH
   ( ) 3:PH__1
   ( ) 3:PH__2

Each "nPerSeason" Trait collects its instances below it.
And you can quickly select "all of the TraitInstances for nPerSeason==2" at the same time. 

Doing it the other way around  the user would get:

 .--- this was where you had the "nPerPlot"
 |
 v
( )  1:PH
   ( ) 1:PH__1 <--- you had this as nPerSeason
   (*) 1:PH__2
   ( ) 1:PH__3

( )  2:PH
   ( ) 2:PH__1
   (*) 2:PH__2
   ( ) 2:PH__3

So to choose "nPerSeason==2" the user would have to expand each of the "nPerPlot" items and then choose the "__2" items individually.

As you can image it gets even worse when you have nPerSeason==12 !

**Comment by celineaubert** [comment]
@omarbenites

- [ ]  Add the TraitLevel colomn in the TraitList tab of the Excel file . the colunm is already in the data dictionnary

**Comment by celineaubert** [comment]
@omarbenites 

- [ ]Info filled in the module Planting and transplanting are not exported in the Excel file.

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] Choice for ''other'' type of experiment are not exported in the Excel file (ex: blabla is missing in the Excel)

![image](https://user-images.githubusercontent.com/14092820/63518970-665cd380-c4f2-11e9-8778-28f686f19df8.png)
![image](https://user-images.githubusercontent.com/14092820/63518949-5ba23e80-c4f2-11e9-9b8d-ea7a1be5f98b.png)

**Comment by celineaubert** [comment]
@omarbenites 
List the project management info about a Project entity toghether (like pic 2)

Currently
 ![image](https://user-images.githubusercontent.com/14092820/63933692-103fe100-ca5a-11e9-89a0-3990a0199560.png)

Info grouped by number
![image](https://user-images.githubusercontent.com/14092820/63933846-5006c880-ca5a-11e9-9b5e-c7338ce0ad2c.png)

**Comment by celineaubert** [comment]
@omarbenites In the Excel file, change ''Row geometry Maize'' to '' Number of row Maize'' (same for all the crop)

AgroFIMS
![image](https://user-images.githubusercontent.com/14092820/63934223-200bf500-ca5b-11e9-95b5-90c80b04c208.png)

Current Excel file
![image](https://user-images.githubusercontent.com/14092820/63934209-18e4e700-ca5b-11e9-898d-904b89bfb2c7.png)

**Comment by celineaubert** [comment]
@omarbenites In Intercropp, protocol info for the second crop is not exported in the Excel file. 

![image](https://user-images.githubusercontent.com/14092820/63934498-d079f900-ca5b-11e9-83d7-41bcdea3b892.png)

![image](https://user-images.githubusercontent.com/14092820/63934512-d66fda00-ca5b-11e9-93ba-9f0ab112709b.png)

**Comment by celineaubert** [comment]
Did not export in the Excel file: Plant density for Maize, and all the info about Planting_Cassava
![image](https://user-images.githubusercontent.com/14092820/63934879-9f4df880-ca5c-11e9-9705-dd04ee439bec.png)
![image](https://user-images.githubusercontent.com/14092820/63934897-aaa12400-ca5c-11e9-99d4-205b3c11336a.png)

**Comment by celineaubert** [comment]
**Timing for Crop Measurement:**
- The value is missing for other
- Days after planting: I did not choose it, it was automatically added. Make sure it's not automatically added to the fieldbook.

![image](https://user-images.githubusercontent.com/14092820/63935114-226f4e80-ca5d-11e9-9f82-3c8e35723142.png)

**Comment by celineaubert** [comment]
**Crop Phenology**

Column alignement issue in the Traitlist
![image](https://user-images.githubusercontent.com/14092820/63935393-a6c1d180-ca5d-11e9-909a-6310ed5f8835.png)

**Comment by celineaubert** [comment]
@omarbenites 
Nomenclature is: (NumberMeaPerSeason):TraitName__(NumberMeaPerPlot)

![image](https://user-images.githubusercontent.com/14092820/63937447-bbed2f00-ca62-11e9-8112-b81412438fd2.png)

**Change the # for :**

**Comment by celineaubert** [comment]
@omarbenites  I have highlighted the tab where the issues are in yellow

[CRD_rice_issues in yellow.xlsx](https://github.com/AGROFIMS/hagrofims/files/3556218/CRD_rice_issues.in.yellow.xlsx)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] CGIAR center name are missing in the list
![image](https://user-images.githubusercontent.com/14092820/64532256-6db51700-d311-11e9-84ce-6903b3499291.png)

![image](https://user-images.githubusercontent.com/14092820/64532300-7e658d00-d311-11e9-9a43-f64025067ae1.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] Affilitation name is missing
![image](https://user-images.githubusercontent.com/14092820/64532398-ae149500-d311-11e9-87bc-82e6a10f44e8.png)

![image](https://user-images.githubusercontent.com/14092820/64532433-c08ece80-d311-11e9-9871-7f836f75372e.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] Factor notes is not listed
![image](https://user-images.githubusercontent.com/14092820/64532634-267b5600-d312-11e9-8877-b9f4f39b33e3.png)

![image](https://user-images.githubusercontent.com/14092820/64532648-3135eb00-d312-11e9-89d0-933df7c44745.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] factor level is written twice
![image](https://user-images.githubusercontent.com/14092820/64533012-ef597480-d312-11e9-9567-f8518be5915e.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] info on Seedbed preparation, Planting and Transplanting,  are not exported(in Protocol and TraitList)

- [ ] Residue info missing in trait lits (from To be collected)
![image](https://user-images.githubusercontent.com/14092820/64533912-c3d78980-d314-11e9-9c64-87f8721dc3d1.png)
![image](https://user-images.githubusercontent.com/14092820/64533933-cd60f180-d314-11e9-8e2f-5e0215f7b41d.png)

- [ ] Weeding info missing
![image](https://user-images.githubusercontent.com/14092820/64534227-5bd57300-d315-11e9-84be-7281e3a9145c.png)

![image](https://user-images.githubusercontent.com/14092820/64534207-511ade00-d315-11e9-80c1-37a8ea4f83aa.png)

- [ ]  Harvest info missing
![image](https://user-images.githubusercontent.com/14092820/64534355-97703d00-d315-11e9-8ba0-0e76dcdf3bed.png)

![image](https://user-images.githubusercontent.com/14092820/64534373-a22ad200-d315-11e9-87ac-ada0d175d579.png)

**Comment by celineaubert** [comment]
- [ ] **Irrigation - To be collected**

- Remove : Surface irrigation, Localized irrigation, Irrigation sprinkler technique from the list 
- Add Irrigation technique (listed in **Datadictionnary**, in tab **Irrigation** line **6**)

![image](https://user-images.githubusercontent.com/14092820/64628924-92cd8680-d3f2-11e9-822f-ff36a63f0004.png)




- [ ] **Crop Phenology - TraitLevel**

Please refer to the DataDictionnary when adding TraitLevel - TraitLevel for Phenology is Subplot

Info in the DataDictionnary:

![image](https://user-images.githubusercontent.com/14092820/64628720-31a5b300-d3f2-11e9-8a0d-681970dda130.png)


Wrong info in Excel file exported from AgroFIMS

![image](https://user-images.githubusercontent.com/14092820/64628656-16d33e80-d3f2-11e9-97f2-c7068eb27b70.png)

**Comment by celineaubert** [comment]
- [ ] **Notes-Deviations - Change the content of this tab**

Delete the current content
![image](https://user-images.githubusercontent.com/14092820/64629546-adecc600-d3f3-11e9-8b15-8aec2bde813d.png)

Replace with column Header : ''Label'', ''Description''
![image](https://user-images.githubusercontent.com/14092820/64629649-df659180-d3f3-11e9-9e68-0e706a3f51be.png)

**Comment by omarbenites** [comment]
- [x] Update Tillage management data

**Comment by celineaubert** [comment]
@omarbenites 
**''other'' type of experiment** 

- [ ]  remove the ''other'' in the list. Keep only the value of ''other'' (here: oth type) but not the name '' other''


![image](https://user-images.githubusercontent.com/14092820/64532047-08f9bc80-d311-11e9-92b8-9fe25338484e.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] review line Header in Excel file

**current names**      -->                                                                **Change to**

Project management center 1               -->                            Project management CGIAR center 1

Project management contributor 1 --> Project management CRP contributor 1

Experiment, lead organization name 1 --> Experiment lead organization 1

Experiment, CGIAR center name 1 --> Experiment lead CGIAR center 1

Experiment, lead contributor crp 1 --> Experiment lead CRP contributor 1

![image](https://user-images.githubusercontent.com/14092820/64705623-87d92b80-d4b0-11e9-9eed-346696481d85.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] In Design, Crop info (when in intercrop) is not exported for the factors where it's needed (harvest date, planting date, crop variety, ...) 
![image](https://user-images.githubusercontent.com/14092820/64706658-25812a80-d4b2-11e9-810f-c24b4c59a59c.png)

![image](https://user-images.githubusercontent.com/14092820/64706616-1601e180-d4b2-11e9-862c-9b0d5623f0e7.png)

**Comment by celineaubert** [comment]
@omarbenites 

**Management practices**

- [ ] When adding a second ''harvest'',''Irrigation'', ''weeding'', info are not reported in Excel. Be careful, when the info are reported they need to be numbered (ex: Harvest_start_date_2)

![image](https://user-images.githubusercontent.com/14092820/64707806-dcca7100-d4b3-11e9-83b3-fd0a9c069e37.png)

**Comment by celineaubert** [comment]
@omarbenites 
Intercrop

- [ ] Some variables are not all reported in Excel. 
- [ ] Also, why Seeding rate for common bean is in lb/ac? put it in kg/ha
![image](https://user-images.githubusercontent.com/14092820/64708550-0f289e00-d4b5-11e9-842c-cfa511c43242.png)

![image](https://user-images.githubusercontent.com/14092820/64708395-d688c480-d4b4-11e9-9014-b27faee37743.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] Info on TraitLevel missing for Phenology

![image](https://user-images.githubusercontent.com/14092820/64710569-7d229480-d4b8-11e9-8662-e6a09cbc9b4d.png)

**Comment by celineaubert** [comment]
@omarbenites 

[fileNameBook (5).xlsx](https://github.com/AGROFIMS/hagrofims/files/3601609/fileNameBook.5.xlsx)

- [ ] Transplanting variables listed in Planting tab but not listed in TraitList

- [ ] TraitAlias are missing for Phenology variables in TraitList

- [ ] Irrigation technique listed in Irrigation tab but not listed in TraitList

- [ ] ''Amount harvested'' listed twice. Keep only Amount_harvested_**kg**

- [ ] Crop_residue_thickness_ft change to Crop_residue_thickness_**cm**

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] In Excel tab name, remove space between Planting-Crop
![image](https://user-images.githubusercontent.com/14092820/64717535-cb3d9500-d4c4-11e9-8d90-1348c4f86886.png)

**Comment by celineaubert** [comment]
- [ ] In Intercrop, KDSmart script doesn't work because there are similar parameter names in the Metadata sheet in Excel
![image](https://user-images.githubusercontent.com/14092820/65683694-34dda780-e05e-11e9-93dc-5f6f61be4b57.png)
![image](https://user-images.githubusercontent.com/14092820/65683750-60609200-e05e-11e9-8604-a8a68c55525f.png)

Change Parameter names for the one below and remove ''Information on experimental unit'':
![image](https://user-images.githubusercontent.com/14092820/65683917-c9480a00-e05e-11e9-9d71-8535dc11bf8f.png)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] The info from Fertilizer management (soil fertility) module in Management practices should go in the Excel sheet called ‘’Fertilizer management’’ and not ‘’soil_sheet‘’. This is the sheet name recognized by KDSMart.
