### ISSUE TITLE
Add ''Implement'' title for the exp conditions

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#167]
For all the experiment conditions with a grey box with Type and Traction variables.

![image](https://user-images.githubusercontent.com/14092820/52722953-ebe45180-2fac-11e9-82d5-f5a3d6da5021.png)

**Comment by ivanperezm** [comment]
![image](https://user-images.githubusercontent.com/40466926/53038407-ae6b4280-344a-11e9-9d5a-f8ff2cb708a7.png)
This issue is solved
