### ISSUE TITLE
Default units for exp. conditions

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#168]
**Residue management**
![image](https://user-images.githubusercontent.com/14092820/52724244-4d0d2480-2faf-11e9-9871-f2879b2c1961.png)

**Puddling**
![image](https://user-images.githubusercontent.com/14092820/52724344-70d06a80-2faf-11e9-88d0-4b9e895d4386.png)

**Tillage**
![image](https://user-images.githubusercontent.com/14092820/52724361-7cbc2c80-2faf-11e9-8ec7-39e9f19ddcf6.png)

**Direct seeding**
![image](https://user-images.githubusercontent.com/14092820/52724464-a9704400-2faf-11e9-8f48-22da3465c2e4.png)

**Transplanting**
![image](https://user-images.githubusercontent.com/14092820/52724773-4501b480-2fb0-11e9-99c4-2dc979a14eca.png)

**Mulch**
![image](https://user-images.githubusercontent.com/14092820/52724824-5ba80b80-2fb0-11e9-9861-543a0fdb7823.png)

**Irrigation**
![image](https://user-images.githubusercontent.com/14092820/52724869-711d3580-2fb0-11e9-9a33-b6eb6599b39c.png)

**Harvest**
![image](https://user-images.githubusercontent.com/14092820/52724934-8a25e680-2fb0-11e9-9685-751b2606b312.png)

**Comment by ivanperezm** [comment]
Dear all,

This issue is solved.
