### ISSUE TITLE
Add a Labbook tab in the Excel fieldbook

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#171]
Labbook tab should contain all the soil measurements.

The soil measurements will appear in the trait list and in the labbook.

**Comment by omarbenites** [comment]
The new version of labbook sheet ( former soil sheet). Fixed for the next update.

![image](https://user-images.githubusercontent.com/5264796/53291117-2489e500-377c-11e9-8478-83cfb1da6488.png)
