### ISSUE TITLE
Merge manual and weather station list in weather module

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#172]
- Name: weather measurement
- Change variables name: weather station to weather measurement (ex: weather station name, to weather measurement location name)

![image](https://user-images.githubusercontent.com/14092820/53178591-6ab33d00-35f2-11e9-90d9-5c8b10270e7d.png)

**Comment by marieALaporte** [comment]
<img width="1193" alt="capture d ecran 2019-02-21 a 16 16 29" src="https://user-images.githubusercontent.com/5664149/53179513-1e68fc80-35f4-11e9-94e8-dd744b26a118.png">

**Comment by marieALaporte** [comment]
the module should look like on the screenshot
