### ISSUE TITLE
statistical analysis

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#177]
- [x] ![image](https://user-images.githubusercontent.com/14092820/54118736-06ff8100-43f4-11e9-8e11-92cbb4dde46d.png)

- [x] Change ''Statistical analysis for one environment trial'' to ''Statistical analysis''

**Comment by ivanperezm** [comment]
Done, But you will see the change in the next link update

**Comment by celineaubert** [comment]
- [ ] Add at the beginning of each stat report the following sentence:

_‘’This is a simple analysis of the data, you may want to pursue this further using more sophisticated models’’_

- [ ] Add ANOVA with all possible factors

- [ ] Remove International Potato Center at the top of the report

- [ ] Add the Experiment Name
![image](https://user-images.githubusercontent.com/14092820/65698985-ae38c280-e07d-11e9-8158-071ff59196bb.png)
