### ISSUE TITLE
Set ''Country'' and ''Village name'' blank

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#187]
If no site data are filled in, the downloaded fieldbook specifies a site in Afghanistan, To avoid it, the ''Country name'' should be blank by default : 

![image](https://user-images.githubusercontent.com/14092820/54539061-be1c6f00-4995-11e9-88b5-ad21f0009937.png)

_(WS March)_

**Comment by omarbenites** [comment]
Referenced by #222
