### ISSUE TITLE
Add more crops to the crop name lists

### ISSUE THREAD

**Issue by frostbytten** [AGROFIMS/hagrofims#19]
This may have to be done in Agro, but add more crops and associated crop measurements.

**Comment by celineaubert** [comment]
Send crops from Crop Ontology @marieALaporte

**Comment by marieALaporte** [comment]
and sort the crops by "type" - the same used in the crop measurement tab

**Comment by celineaubert** [comment]
CGIAR mandate crop added in AgroFIMS

- [x] sorghum
- [x] Pearl millet
- [x] Finger Millet
- [x] teff
- [x] bananas
- [ ] plantains
- [x] barley
- [x] chickpea
- [x] lentils
- [x] faba bean
- [x] grasspea
- [x]  Pigeonpea
- [x] Groundnut
- [x] yam

**Comment by celineaubert** [comment]
plantains has not been added. It could be added later, if there is a request from users for it.
