### ISSUE TITLE
Add weeding product and amount factor

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#191]
Make this work like the fertilizer product and amount feature
- [x]  1- select the weeding product
2- select the info you wish to give about it (product rate, product amount)

![image](https://user-images.githubusercontent.com/14092820/54542053-5cf79a00-499b-11e9-9373-33bc68766f10.png)

(WS March, Pieter)

**Comment by celineaubert** [comment]
Link 
![image](https://user-images.githubusercontent.com/14092820/54542287-d2636a80-499b-11e9-9dc4-b054ee2b6793.png)

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/54542625-74835280-499c-11e9-9a08-233d7f8c594e.png)

_(WS March, Pieter)_

**Comment by celineaubert** [comment]
- [ ] implement a search search function among all the treatment - we should use the synonyms to make it robust (ex: ploughing and tillage). Search box at the top. when you find your factor, you click enter and the form is created below (Pieter). 

- [ ] change the sentence ‘’look at the tab at the top’’ when fertilizer is selected. Users don’t find the tabs

- [ ] no need to click on ‘’book preview’’ to see the preview. should be automatic. User don’t see it

- [ ] Find a better way to show where people forgot to enter one level 
(green tick?) (when book preview is not available because all level have not been filled)

- [ ] When you select fertilizer nutrient rate: see only nutrient application rate, not fertilizer application rate

- [ ] For fertilizer type: be able to select the type of fertilizer. no need to have the factor table. 

- [ ] In non full factorial: fertilizer rate, have the treatment in a tab next to the level (Pieter)

- [ ] When ''Other'' is selected, open a text box to fill in the name of the treatment

- [ ] weeding: be able to compare different chemical product, different rate for those fertilizer

- [ ] weeding: high-frequency weeding vs low-frequency weeding

- [ ] Mulch: Be able to select ''leaves'' more than once, and to specify from which plant they are from  (leaves of plant X and leaves of plant Y). 

- [ ] Possibility to have only 1 replication (in multi location, a farmer is a replication. so 1 replication per location) (Pieter)

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/54615600-abba3800-4a5e-11e9-8be7-3f17272be10e.png)

What if I need three factors that apply to the main plot, and then one that applies to the sub-plot?  Not clear how to enter.
_(WS March)_

**Comment by celineaubert** [comment]
In Full factorial, if it's mandatory to have 2 factor minimum, find a way to inform the user (ex: hide the x)![image](https://user-images.githubusercontent.com/14092820/54623573-145be180-4a6c-11e9-8839-0c588c69e5a6.png)

**Comment by celineaubert** [comment]
Duplicate button in the ''Soil fertiliy details-  factor''
![image](https://user-images.githubusercontent.com/14092820/54624067-f5aa1a80-4a6c-11e9-8c46-e0c675c068b4.png)

**Comment by omarbenites** [comment]
Hey guys,
I have upload the slides from the last meeting 21/03/2019. Click to download

[Improvement_AGROFIMS_20-03-2019.pptx](https://github.com/AGROFIMS/hagrofims/files/2992943/Improvement_AGROFIMS_20-03-2019.pptx)

Regards,

Omar

**Comment by omarbenites** [comment]
Improvements for the 9 April, 2019
![image](https://user-images.githubusercontent.com/5264796/55103600-c90e8800-5096-11e9-981b-cfe46304b779.png)

CRD AND RCBD

![image](https://user-images.githubusercontent.com/5264796/55103612-cf9cff80-5096-11e9-9855-4db21dd504dd.png)

FACTORIAL WITH CRD AND RCBD

![image](https://user-images.githubusercontent.com/5264796/55103721-03782500-5097-11e9-9f14-8bc0e00c1dc6.png)

Seach Box in Design

![image](https://user-images.githubusercontent.com/5264796/55103624-d592e080-5096-11e9-88e5-c8abe92a4c4c.png)


Other Factors

![image](https://user-images.githubusercontent.com/5264796/55103635-da579480-5096-11e9-849c-961f521cb4d4.png)


Other levels

![image](https://user-images.githubusercontent.com/5264796/55103651-e0e60c00-5096-11e9-9549-f2145df9db8a.png)

**Comment by celineaubert** [comment]
**Some modifications to simplify the interface**

![image](https://user-images.githubusercontent.com/14092820/55950054-4e2b9c80-5c54-11e9-82fd-2ac189fd4ae0.png)

**Final page:**
![image](https://user-images.githubusercontent.com/14092820/55949946-0d338800-5c54-11e9-87f5-2e47c2a426cd.png)

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/55950912-4a007e80-5c56-11e9-84b4-8f609c286470.png)

**Comment by celineaubert** [comment]
Other factor

![image](https://user-images.githubusercontent.com/14092820/55951863-92b93700-5c58-11e9-8bf8-b457729d8d1e.png)

**Comment by celineaubert** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/14092820/56742631-6a136000-6775-11e9-8f33-74e36a75adeb.png)

**Comment by celineaubert** [comment]
- [ ] weeding: be able to compare different chemical product, different rate for those fertilizer
 

- [ ] Possibility to have only 1 replication (in multi location, a farmer is a replication. so 1 replication per location) (Pieter)

**Comment by omarbenites** [comment]
- [ ] weeding: be able to compare different chemical product, different rate for those fertilizer

- [ ] Possibility to have only 1 replication (in multi location, a farmer is a replication. so 1 replication per location) (Pieter (for second release)

**Comment by omarbenites** [comment]
✅  Until these comments, all these issues has been fixed.

**Comment by omarbenites** [comment]
New issues for the second release ( 2️⃣  ):

- [ ] weeding: be   able to compare different chemical product, different rate for those   fertilizer

- [x] Possibility to have only 1   replication (in multi location, a farmer is a replication. so 1 replication   per location) (Pieter (for second release)

**Comment by celineaubert** [comment]
For **weeding prodcut and amount** factor, could we have the same format that the other ''type and amount'' factor, with a box for the prodcut name, a box the the level, and another one for the unit?
![image](https://user-images.githubusercontent.com/14092820/100215410-3e3bfb80-2f11-11eb-83a6-bb6e5523901c.png)

**Comment by omarbenites** [comment]
Hi Celine, this type of improvement, we will move for the next year.

**Comment by celineaubert** [comment]
moved as issue #288
