### ISSUE TITLE
Change ''Soil fertility'' to ''Fertilizer management''

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#198]
![image](https://user-images.githubusercontent.com/14092820/54746864-91eb3300-4bcd-11e9-9d52-9c37a1951b1f.png)

**Comment by celineaubert** [comment]
@omarbenites 
this is not done

![image](https://user-images.githubusercontent.com/14092820/66109702-85f11c80-e5c5-11e9-8017-433550860dee.png)

**Comment by omarbenites** [comment]
Referenced by #222
