### ISSUE TITLE
Add ''Green manure'' to Crop

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#199]
![image](https://user-images.githubusercontent.com/14092820/54756548-c1f3ff80-4be8-11e9-993d-804488722d3f.png)

1.  If  ''Green manure'' is selected, a pop-up box appears with a list of green manure crops. The list is in AgroFIMS_Agronomy_DataDictionary_21-3-2019 --> Fertilizer management--> Fertilizer type --> Green manure
 
![image](https://user-images.githubusercontent.com/14092820/54757052-bce38000-4be9-11e9-996d-322253e20450.png)

2.  If ''Other is selected in this pop-up box, then a text box will pops-up

![image](https://user-images.githubusercontent.com/14092820/54756401-72adcf00-4be8-11e9-9508-2cf272960f47.png)

**Comment by omarbenites** [comment]
Issue referenced in  #222
