### ISSUE TITLE
save fieldbook feature

### ISSUE THREAD

**Issue by marieALaporte** [AGROFIMS/hagrofims#2]
to persist all the information in all tabs

**Comment by ivanperezm** [comment]
Dear All,

The session stores information of the following tabs:
https://apps.cipotato.org/hidapagrofimsv021/

- Experiment
- Personnel
- Site
- Crop
- Experiment conditions

**Comment by ivanperezm** [comment]
To keep the information of the other tabs, before they should be clear and defined.

**Comment by celineaubert** [comment]
Only ''Experiment details'' info are stored

**Comment by celineaubert** [comment]
Order of the different buttons in the ''Save'' module
![image](https://user-images.githubusercontent.com/14092820/62632297-8c02ae00-b932-11e9-953d-5432a1988559.png)
