### ISSUE TITLE
Have frequency, DAP, growth stage, as measurement date

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#202]
For each measurement and some experimental conditions enable the selection of: *number of measurements, * at growth stage, or * frequency *days after planting (DAP)

- If it is “number of measurements”: how many?
- For frequency : time interval in days
- For growth stage, choose from a list which is based on the crop. Maybe stick to anthesis and maturity to begin and allow the user to enter other stages. This is only for the field person to use. All measurements will be associated with a date when measured.
- For planting: ‘’number of days after planting’’

**Comment by celineaubert** [comment]
Crop measurement mock-up @ivanperezm @omarbenites 


![image](https://user-images.githubusercontent.com/14092820/56962117-0bbff600-6b56-11e9-9e63-1137495938e8.png)

**Comment by omarbenites** [comment]
Notes

- Trait Unit -----> Unit (Just in the interface)
- Day after planting ---> `Days after planting` (with s)`
- Parameter values should depend/filter by `Crop` and `Measurement`
- Unit value should depend of `Crop` and `Measurement`
- Select placeholder ----> `Seach crop measurement`
- Add a box number of `Number of Dates/Growth Stage/

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/57700653-b6f2a400-765a-11e9-965b-32b279fafe3f.png)

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/57702030-7ba5a480-765d-11e9-9ec6-b81935a022fd.png)

**Comment by celineaubert** [comment]
Experimental conditions:
Have ''Timing'' for Fertilizer, Irrigation and Weeding. 

I did the modifications in the DataDictionnary

 ![image](https://user-images.githubusercontent.com/14092820/57707199-7d746580-7667-11e9-84d4-dde8f771faf9.png)

How it could look like in AgroFIMS
![image](https://user-images.githubusercontent.com/14092820/57707532-16a37c00-7668-11e9-86a1-962b78a35d2b.png)

**Comment by celineaubert** [comment]
Column headers
Per season --> Samples per season
Per plot --> Samples per plot

**Comment by celineaubert** [comment]
Hi,
KDSmart, can not take into account the column ''timing'' and timing value'' in the protocol tab. 
One solution could be to create a line for each timing. For example, if user gives a timing for irrigation, we could create a line in the protocol tab: 
 **TraitName      .....................................         Value**
Irrigation_amount ........................... 200mm
Irrigation_timing      .......................               . every 10 days
