### ISSUE TITLE
Changes made in the data dictionary and Crop-measurement

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#203]
- [x] Added new variables in Crop_measurement that need VariableIds

**Comment by STOALM** [comment]
- [ ] Crop_measument_22-3-2019: added missing IDs (933)
https://docs.google.com/spreadsheets/d/1nx1MDdWkc57dIIcME89Pao_7dEQdvoZQoYrIDB_KrZA/edit#gid=1065388546
- [ ] Soil_22-3-2019: added missing ID (934)
https://docs.google.com/spreadsheets/d/1oSfmuTmE-Z4sevI_A52qFm7EFMMykfgkLhcZxqC3erI/edit#gid=1100801291

**Comment by omarbenites** [comment]
- [x] Factor_Design Table V10.Draft : Added some form type in `Irrigation technique` and `Nutrient toxicity type`
https://docs.google.com/spreadsheets/d/1M5KA4JTqd1zdv1p-Gu5kfsLNi8WHWAyCMvCNBDa9G_Y/edit#gid=1932177125

**Comment by celineaubert** [comment]
- [ ] filled in the ''Multicrop'' column in the file Factor v10

**Comment by STOALM** [comment]
- [ ] AgroFIMS_Agronomy_DataDictionary_21-3-2019: added missing IDs (935 & 936)

**Comment by celineaubert** [comment]
- [ ] I added new variables

- [ ] @STOALM could you add variableID for them (variable ID case is in yellow)

**Comment by STOALM** [comment]
All variables IDs have been aligned to the new ranges. Thank you @celineaubert

**Comment by celineaubert** [comment]
I have added new factors and new ''interface comments'', on ''timing'' and ''amount'' factor. let me know if you explanation are needed.
