### ISSUE TITLE
New interface when ''amount'' is a factor

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#211]
When one of the following factor is selected:
- Fertilizer amount
- Fertilizer type
- Irrigation amount and - Mulch amount  -----> 
- mulch type
- Biotic stress type
- Biotic stress control product amount
- Crop residue

The following boxes should appear:
- Select ... : Combo box with one choice of type of irrigation, fertilizer, mulch, biotic stress, crop residue 
- Enter levels : text box with multiple inputs
-Unit:  unit box
- Ad button

![image](https://user-images.githubusercontent.com/14092820/57088205-0dc6b800-6d02-11e9-989a-e8d552ca7ba9.png)

**Comment by omarbenites** [comment]
Priority Order

- Fertilizer amount and Fertilizer type  ---------->  Fertilizer amount and type
- Irrigation amount and Irrigation type --------------->  Irrigation amount type
- Mulch type and mulch amount  ---------->  mulch type and amount
- Biotic stress type
- Biotic stress control product amount
