### ISSUE TITLE
AGROFIMS and KDSmart Integration

### ISSUE THREAD

**Issue by omarbenites** [AGROFIMS/hagrofims#213]
Trait list - missing Headings: MEASUREMENT, MEASURES_PER_SEASON, MEASURES_PER_PLOT, TRAIT_UNIT, TRAIT_NAME

Metadata - missing Headings: VALUE

[Metadata].Row#1 : Missing VALUE

[Trait list].Row#1 : Missing MEASURES_PER_PLOT, TRAIT_UNIT, MEASUREMENT, MEASURES_PER_SEASON, TRAIT_NAME

**Comment by celineaubert** [comment]
@omarbenites 
-	KDMSart tool does not consider the sheets: Harvest, Planting, Phenology and Crop_measurements (this is the case for monocrop experiments)
Could you please add these sheet names in the tool you have integrate to AgroFIMS? You need to click on the + button and enter the name on the sheet one by one:
![image](https://user-images.githubusercontent.com/14092820/63954770-ed2a2700-ca83-11e9-8f6d-85dacb7b65f1.png)

I did it manually for the tool on my laptop
![image](https://user-images.githubusercontent.com/14092820/63954793-f7e4bc00-ca83-11e9-9728-640fbdbab8df.png)

**Comment by celineaubert** [comment]
Brian's script has been updated by Marie
