### ISSUE TITLE
Add the title ''Soil group'' in Site module

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#218]
- [x] Add the title ''Soil group'' in Site module ![image](https://user-images.githubusercontent.com/14092820/62526465-97be7980-b839-11e9-8a44-9faab61b1274.png)

- [x] Add a line '' Soil group'' in the Excel File (currently, the name of the soil group is not reported in the Excel file)

![image](https://user-images.githubusercontent.com/14092820/62526533-b9b7fc00-b839-11e9-9740-c154d94a55c0.png)

**Comment by omarbenites** [comment]
- Check the next updated link.

**Comment by celineaubert** [comment]
done

**Comment by celineaubert** [comment]
@omarbenites 

Can you write:

- [ ] Soil **g**roup (with a little g) in AgroFIMS

- [ ] **Soil group** in the Excel (not Soil classification group)
