### ISSUE TITLE
Typo: type of traction for transplanting

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#219]
**Change Traction to Manual**

In the data dictionary we have ''Manual''
![image](https://user-images.githubusercontent.com/14092820/62528552-516b1980-b83d-11e9-82c3-67f2e4c4cc55.png)

But in AgroFIMS we have ''Traction''
![image](https://user-images.githubusercontent.com/14092820/62528590-621b8f80-b83d-11e9-9440-517265944193.png)

**Comment by omarbenites** [comment]
Fixed issue.
