### ISSUE TITLE
Add column in crop measurement to enter the number of measurement

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#22]
Add 2 columns in the crop measurement module in the interface to specified (in the same row) how many times it will be measured during the season and how many measure are needed per measurement. The fieldbook needs to take the result into account by having as many row as needed. Numbering: 1_1, 1_2, 2_1, 2_2.

in AgroFIMS
![picture5](https://user-images.githubusercontent.com/14092820/52295511-fddd4900-2949-11e9-8c13-0585aa0f4990.png)

**Comment by reyzaguirre** [comment]
Then in the fieldbook we must have additional columns for the different measurements. One option for labels could be: TRAIT.S#.M#. So let us suppose we have 2 seasons and 3 measurements per plot for trait ABC, then in the fieldbook we have columns for:
ABC.S1.M1   ABC.S1.M2   ABD.S1.M3   ABC.S2.M1   ABC.S2.M2   ABD.S2.M3

In this way we can distinguish measures for different seasons and on the same plot. Typically, the user will want to have a statistic (a sum or an average) for the measurements in the same plot, and then we can easily identify these values with the M# indicator.

**Comment by celineaubert** [comment]
add the columns in Weather as well

**Comment by celineaubert** [comment]
Titles of column are:
- Number of measurement per season
- Number of measurement per plot

![image](https://user-images.githubusercontent.com/14092820/53961749-9ef62580-40e9-11e9-9f96-a36dbfc414c1.png)

**Comment by celineaubert** [comment]
available in v22
