### ISSUE TITLE
Interface enhancement

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#222]
- [x]  give a area unit to Number of row (issue for Celine)
![image](https://user-images.githubusercontent.com/14092820/63951767-a128b380-ca7e-11e9-971c-1666b8a9846f.png)

**Comment by celineaubert** [comment]
- [ ] Change Refresh to New , remove Experiment description, remove last modified (it does not work)

![image](https://user-images.githubusercontent.com/14092820/67492764-3909de80-f677-11e9-8172-c62536e0b769.png)



- [ ]  The QRCode only gives the name of the Experiment. Hide the QRcode for now.
![image](https://user-images.githubusercontent.com/14092820/67491319-0a8b0400-f675-11e9-9b16-15bbe766f3d8.png)

- [ ] Create Site
![image](https://user-images.githubusercontent.com/14092820/67491655-8a18d300-f675-11e9-8a9c-6746691c5df4.png)

- [ ] Site map
![image](https://user-images.githubusercontent.com/14092820/67491973-07444800-f676-11e9-9000-5efca5a6a611.png)

- [ ] Site map
![image](https://user-images.githubusercontent.com/14092820/67492275-7457dd80-f676-11e9-843e-fe77ca0dc710.png)

- [ ] List Sites
![image](https://user-images.githubusercontent.com/14092820/67492517-d3b5ed80-f676-11e9-9612-b0b22b08813f.png)

- Site in Fieldbook
![image](https://user-images.githubusercontent.com/14092820/67493244-e7158880-f677-11e9-8f92-2611b3d9372c.png)


- [ ] Crop - Monocrop
![image](https://user-images.githubusercontent.com/14092820/67494825-280e9c80-f67a-11e9-9925-6bd96b62b4a3.png)

Final look
![image](https://user-images.githubusercontent.com/14092820/67495056-90f61480-f67a-11e9-90d2-b3213af92cb6.png)

- [ ] Crop -Intercrop and relay crop
![image](https://user-images.githubusercontent.com/14092820/67496898-6fe2f300-f67d-11e9-8d55-c346e95b2b31.png)

Final look
![image](https://user-images.githubusercontent.com/14092820/67498446-c3564080-f67f-11e9-8cbb-8cbf106ac827.png)


- [ ] Intercrop and relay crop  - pu
![image](https://user-images.githubusercontent.com/14092820/67497803-cbfa4700-f67e-11e9-9b87-935979fe5598.png)

Final look
![image](https://user-images.githubusercontent.com/14092820/67498104-3612ec00-f67f-11e9-834f-b5c006642b2f.png)




- [ ] Design

![image](https://user-images.githubusercontent.com/14092820/67493881-ab2ef300-f678-11e9-9095-c0855e8766b7.png)

- [ ] Design
![image](https://user-images.githubusercontent.com/14092820/67493936-c0a41d00-f678-11e9-995c-ebac9f8321c8.png)


- [ ]  Design - Factor

Would it be possible to have the pink boxes in light blue or in white and the pink buttons in the same blue than the other buttons (like Next) in the website, to keep an harmony?
![image](https://user-images.githubusercontent.com/14092820/67498542-e7b21d00-f67f-11e9-8c4b-79040c4d1070.png)

- [ ]  Management practices - Planting transplanting

Remove the outside rectangle to have the same design than Residue Management 
![image](https://user-images.githubusercontent.com/14092820/67498911-83dc2400-f680-11e9-8622-d8e21cc4b4f2.png)

- [ ] Management practices - rename
![image](https://user-images.githubusercontent.com/14092820/67499120-d289be00-f680-11e9-90be-e51dcb4f4c38.png)

- [ ] Crop measurement
![image](https://user-images.githubusercontent.com/14092820/67499972-3b256a80-f682-11e9-8a8a-09edd6b81d1b.png)

- [ ] Weather measurement
![image](https://user-images.githubusercontent.com/14092820/67500054-67d98200-f682-11e9-89ac-9ea984ca4e92.png)

- [ ] Soil measurement
![image](https://user-images.githubusercontent.com/14092820/67500194-a1aa8880-f682-11e9-8f93-5cf1522da89d.png)

- [ ] Manage fieldbook
![image](https://user-images.githubusercontent.com/14092820/67500540-1f6e9400-f683-11e9-8c89-93c5d238a1b4.png)

- [ ] Export fieldbook
![image](https://user-images.githubusercontent.com/14092820/67500614-3d3bf900-f683-11e9-988d-76765e252166.png)

**Comment by celineaubert** [comment]
- [ ] Change the confirmation email to:

Hi Name Familyname!

Welcome to AgroFIMS and thank you for signing up!
To confirm your account, please click on the following link:

https://research.cip.cgiar.org/gtdms/hidap/agrofims/accountConfirmation.php?key=f263600e0b1968b8d393d79210202c60111e71a25a42b6024ef14e36926adb79dd37b79dd3eb616b6ed 

Hope you will enjoy it! 

Best regards,
The AgroFIMS team

**Comment by ivanperezm** [comment]
Done

**Comment by celineaubert** [comment]
Hi Ivan, 
Have you updated a link with the enhancements of this issue? If yes, could you share it with me?
Thanks!

**Comment by omarbenites** [comment]
Hi Celine, sorry we closed this issue by mistake. Ivan pointed out https://github.com/AGROFIMS/hagrofims/issues/222#issuecomment-547037766

**Comment by omarbenites** [comment]
- [ ]  Management practices - Planting transplanting

Remove the outside rectangle to have the same design than Residue Management 
![image](https://user-images.githubusercontent.com/14092820/67498911-83dc2400-f680-11e9-8622-d8e21cc4b4f2.png)

- [ ] Management practices - rename Soil fertility
![image](https://user-images.githubusercontent.com/14092820/67499120-d289be00-f680-11e9-90be-e51dcb4f4c38.png)

- [ ] Management practice- Fertilizer management - Nutrient
![image](https://user-images.githubusercontent.com/14092820/67857838-10bb2d80-fb18-11e9-9199-36ce0e5b91b8.png)

- [ ] Management practice- Fertilizer management - Fertilizer
![image](https://user-images.githubusercontent.com/14092820/67857913-419b6280-fb18-11e9-869e-a6bcee8f7504.png)


- [ ] Crop measurement
![image](https://user-images.githubusercontent.com/14092820/67499972-3b256a80-f682-11e9-8a8a-09edd6b81d1b.png)

- [ ] Weather measurement
![image](https://user-images.githubusercontent.com/14092820/67500054-67d98200-f682-11e9-89ac-9ea984ca4e92.png)



D
Derived from Celines's comment


- [ ] Soil measurement
![image](https://user-images.githubusercontent.com/14092820/67500194-a1aa8880-f682-11e9-8f93-5cf1522da89d.png)

- [ ] Manage fieldbook
![image](https://user-images.githubusercontent.com/14092820/67500540-1f6e9400-f683-11e9-8c89-93c5d238a1b4.png)

- [ ] Export fieldbook
![image](https://user-images.githubusercontent.com/14092820/67500614-3d3bf900-f683-11e9-988d-76765e252166.png)

**Comment by omarbenites** [comment]
![image](https://user-images.githubusercontent.com/14092820/54756548-c1f3ff80-4be8-11e9-993d-804488722d3f.png)



1.  If  ''Green manure'' is selected, a pop-up box appears with a list of green manure crops. The list is in AgroFIMS_Agronomy_DataDictionary_21-3-2019 --> Fertilizer management--> Fertilizer type --> Green manure
 
![image](https://user-images.githubusercontent.com/14092820/54757052-bce38000-4be9-11e9-996d-322253e20450.png)


2.  If ''Other is selected in this pop-up box, then a text box will pops-up

![image](https://user-images.githubusercontent.com/14092820/54756401-72adcf00-4be8-11e9-9508-2cf272960f47.png)

**Comment by omarbenites** [comment]
@omarbenites 
 In design change number of splits to number of applications for
- [ ] Crop residue amount

- [ ] Biotic stress control product type and amount

- [ ] Mulch type and amount

![image](https://user-images.githubusercontent.com/14092820/65956000-a98f5800-e449-11e9-9450-4181bd2d90f3.png)

- [ ] If possible keep '' Number of splits'' for fertilizer and nutrient type and amount

**Comment by omarbenites** [comment]
@omarbenites 
 In design change number of splits to number of applications for
- [ ] Crop residue amount

- [ ] Biotic stress control product type and amount

- [ ] Mulch type and amount

![image](https://user-images.githubusercontent.com/14092820/65956000-a98f5800-e449-11e9-9450-4181bd2d90f3.png)

- [ ] If possible keep '' Number of splits'' for fertilizer and nutrient type and amount

**Comment by omarbenites** [comment]
If no site data are filled in, the downloaded fieldbook specifies a site in Afghanistan, To avoid it, the ''Country name'' should be blank by default : 

![image](https://user-images.githubusercontent.com/14092820/54539061-be1c6f00-4995-11e9-88b5-ad21f0009937.png)


_(WS March)_

**Comment by celineaubert** [comment]
- [ ] Management practice- Fertilizer management - Product
![image](https://user-images.githubusercontent.com/14092820/69064331-4c159180-0a1e-11ea-8a3a-c4211f0ce347.png)

**Comment by celineaubert** [comment]
Hi @Omar and @ivanperezm thank you for making the above changes. Below are some comments on them

- [ ] Site tab: bug when changing the size of the window: the two buttons are overlapping
![image](https://user-images.githubusercontent.com/14092820/70055255-7dbf5880-15d9-11ea-9297-1e1397f1f461.png)

- [ ] Crop tab: typos: arrangement and geometry
![image](https://user-images.githubusercontent.com/14092820/70055492-ec9cb180-15d9-11ea-97d9-9f9e47bc0546.png)

- [ ] Design- Factor - Fertilizer type and amount
Change rowname by Factor or Treatment (the change does not appear in V026) ![image](https://user-images.githubusercontent.com/14092820/70055989-f541b780-15da-11ea-9955-c257a09fa26e.png)

- [ ]  Crop measurement : changes do not appear in V026
![image](https://user-images.githubusercontent.com/14092820/70056491-d5f75a00-15db-11ea-8a4d-b23cc852efe1.png)

![image](https://user-images.githubusercontent.com/14092820/70056385-aa746f80-15db-11ea-923f-95566c036102.png)

- [ ] Weather measurement: set timing blank
![image](https://user-images.githubusercontent.com/14092820/70056567-f58e8280-15db-11ea-9373-b0be04593163.png)

- [ ] Soil measurement: set timing blank
![image](https://user-images.githubusercontent.com/14092820/70056675-25d62100-15dc-11ea-9714-2c49a520b14f.png)

- [ ] List of green manure in Crop tab. It is better to use the list in the Excel file: fertilizers 14-11- nutrient content
![image](https://user-images.githubusercontent.com/14092820/70056940-99782e00-15dc-11ea-8928-1d55d13ec6f7.png)

- [ ] Management practice- Fertilizer management - Product
![image](https://user-images.githubusercontent.com/14092820/70057327-3a66e900-15dd-11ea-9798-e8b5b4e9d15f.png)

**Comment by celineaubert** [comment]
Hi @omarbenites could you please add the units for Number of row, in Management practices>Planting, transplanting > direct seeding and transplanting? Units are listed in the Excel file: https://docs.google.com/spreadsheets/d/17k_gmu0yPMY3q25hp602_wYo4vOL-JzOONoMfqnZn-Y/edit#gid=2146395440

![image](https://user-images.githubusercontent.com/14092820/70239399-85af0200-176b-11ea-849b-4d4effc3de3c.png)


![image](https://user-images.githubusercontent.com/14092820/70239362-7465f580-176b-11ea-82be-2cadab58316a.png)

**Comment by celineaubert** [comment]
(first and) Last task not done- Opened a new issue #256 only for this task.
