### ISSUE TITLE
Interface in AgroFIMS to upload KDSmart file and embed Marie's script

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#223]
Create an interface in AgroFIMS for users to download the KDSmart files, and then read them for analysis

 **Workflow for file from KDSmart to AgroFIMS**

- [x] .Users import KDX file in their lapotop
- [x] Users upload the file in AgroFIMS **(Need an interface)**
- [x] AgroFIMS reads the file thanks to Marie’s script
- [x] Users can download the file in Excel format
- [x] AgroFIMS can use the file for Analysis

**Comment by omarbenites** [comment]
The marie's script has been installed in the agrofims server. 👍
