### ISSUE TITLE
Bug when selecting ''Other'' for Implement type in Land levelling

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#224]
The fieldbook can't be downloaded if ''Other'' is selected.
![image](https://user-images.githubusercontent.com/14092820/64704340-6e36e480-d4ae-11e9-8bfc-bb6a634b1fc2.png)

![image](https://user-images.githubusercontent.com/14092820/64704410-873f9580-d4ae-11e9-9338-b8617cb97f8b.png)

**Comment by omarbenites** [comment]
Fixed for the next update ✅
