### ISSUE TITLE
Update the confirmation email text

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#225]
Hi Name Last name!

Welcome to HiDAP-AgroFIMS and thank you for signing up!
To activate your account, please click on the following link:
 LINK

Once you have confirmed your account, you can start using HiDAP-AgroFIMS.
Hope you will enjoy it! 

Best regards,
The HiDAP-AgroFIMS team

**Comment by ivanperezm** [comment]
Done
