### ISSUE TITLE
Change your password

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#226]
![image](https://user-images.githubusercontent.com/14092820/67490168-170e5d00-f673-11e9-965c-726c9ac37c11.png)
- [] 

 - [x] reset password message ends up in my Spam.  ✅ 

- [ ] Once a user changes their password successfully, the screen '' Password change'' should not show up – only the message saying “Your password has been successfully changed.” Nothing else.

**Comment by omarbenites** [comment]
Fixed for the next update v26.
