### ISSUE TITLE
Add ''Create a new site'' button in Site information

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#228]
![image](https://user-images.githubusercontent.com/14092820/66135986-0aaa5d80-e5fb-11e9-9c39-7386e32c8d70.png)

**Comment by celineaubert** [comment]
Put the 2 buttons below the Site dropdown bar, to harmonize the page:
Also, the text in the 2 button can be shorten (see picture)

![image](https://user-images.githubusercontent.com/14092820/67399472-96852900-f5ac-11e9-9b36-e9dc0ae262b5.png)

**Comment by omarbenites** [comment]
Issue referenced in #222
