### ISSUE TITLE
no need to check the box in measurement practices to select them

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#232]
This is not obvious and users may miss to check the box (I forgot it all the time).
Maybe the box can be automatically checked if users filled information in this section?

![image](https://user-images.githubusercontent.com/14092820/66479087-0e772d80-ea9c-11e9-8166-02f65c499b3b.png)

- residues management
- planting
- seedbed preparation

**Comment by omarbenites** [comment]
- Fixed for the next update ✅
