### ISSUE TITLE
Update the text in the pop-up window when a new account is created

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#233]
Users can connect without receiving the confirmation email. Therefore, the text in the pop-up window has to be updated. 

![image](https://user-images.githubusercontent.com/14092820/67466654-b87fb980-f647-11e9-844e-ae8db98454a0.png)

New text: **Your account has been successfully created. You can now log in and start using AgroFIMS.**
Also change the title of the box to : **AgroFIMS**, and the text in the bottom button to : **OK**
![image](https://user-images.githubusercontent.com/14092820/67501446-92c4d580-f684-11e9-9a5a-f093fb9b1332.png)

**Comment by celineaubert** [comment]
v026 - 
![image](https://user-images.githubusercontent.com/14092820/68782169-3c223a00-0639-11ea-95de-5964dc7c1f20.png)

Would it be possible to remove the space between the 2 lines, and reduce the font size?

**Comment by omarbenites** [comment]
- Fixed for the next update. ✅
