### ISSUE TITLE
Add WRB for soil classification

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#235]
https://en.wikipedia.org/wiki/World_Reference_Base_for_Soil_Resources#The_WRB_2015

**Comment by celineaubert** [comment]
list added here: https://docs.google.com/spreadsheets/d/1whG77uKTYb6TJtLFIK7GkmH8Nk3haoFAtUvg78F3jKU/edit#gid=1720980559

@omarbenites , could you please add it in AgroFIMS?

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
done in v 0369
![image](https://user-images.githubusercontent.com/14092820/102332712-c2bbf000-3f8c-11eb-8f4f-e7f934cda035.png)
