### ISSUE TITLE
Add a contact section in the site

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#240]
add a contact section with a email address people can use for assistance

**Comment by celineaubert** [comment]
see if it is possible to have a agrofims@cgiar.org address

**Comment by celineaubert** [comment]
the email address (agrofims@cgiar) has been created

**Comment by omarbenites** [comment]
Place the email in the bottom right corner

![Uploading image.png…]()

**Comment by celineaubert** [comment]
@omarbenites there is a white space after the email address. Could you remove it? On my smaller laptop screen, I can not see the full address

17'' screen:
![image](https://user-images.githubusercontent.com/14092820/71012366-51363100-20ef-11ea-836a-1b74644edc87.png)

13'' screen
![image](https://user-images.githubusercontent.com/14092820/71012531-90648200-20ef-11ea-86c5-c95f9eb2e1bd.png)
