### ISSUE TITLE
Allow ''Other'' management practices

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#241]
- [ ] Add ''Other'' to the list of management practicies

![image](https://user-images.githubusercontent.com/14092820/68386382-2fdf3e00-015c-11ea-854e-9b48a9bb8a7b.png)

- [ ] When '' Other'' is selected, blank boxes appear to allow users to create their own management practices. (it should work like ''other'' in Factor) - Only one value (one date, one number) per line.

![image](https://user-images.githubusercontent.com/14092820/68386507-7765ca00-015c-11ea-8218-13f6083491fa.png)

- [ ] These new management practices are exported in the Excel tab Protocol
Management practices name --> Trait Name
Value--> Value
Unit--> TraitUnit

**Comment by omarbenites** [comment]
@celineaubert This feature is more time-consuming than we expect. Let us move to the second release.
