### ISSUE TITLE
Factors Type and amount

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#243]
Change the button ''add fertilizer'' to ''add type'' for the following factors

- [x] Irrigation

- [x] Mulch

- [x] Biotic stress type

- [x] Biotic stress contro; product
 ![image](https://user-images.githubusercontent.com/14092820/68899238-81299780-0731-11ea-99c7-8eca1531fc01.png)

@omarbenites sorry to add this to the First release. I am not sure were to add it. But we can not make a first release with this ''error'' that can be confusing for the user.

**Comment by celineaubert** [comment]
@mdevare should we keep ''Number of split'' for irrigation, mulch and biotic stress in factor?
![image](https://user-images.githubusercontent.com/14092820/68899681-7f140880-0732-11ea-8dab-c4abf8e7e335.png)

![image](https://user-images.githubusercontent.com/14092820/68899713-8affca80-0732-11ea-8163-dcfc6a96a370.png)

![image](https://user-images.githubusercontent.com/14092820/68899735-9652f600-0732-11ea-9cc5-7b1b9cfe2231.png)

**Comment by omarbenites** [comment]
@celineaubert we changed as you suggest in https://github.com/AGROFIMS/hagrofims/issues/227

Now look like this 
![image](https://user-images.githubusercontent.com/5264796/69168404-994c3e80-0ac4-11ea-9bf1-c2e9059a02e8.png)
