### ISSUE TITLE
Add terms of use and policy text

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#246]
- [ ] add them in the website 

- [ ] and in the Log In pop up window
![image](https://user-images.githubusercontent.com/14092820/72989327-51aca080-3dee-11ea-8054-4e750a162d4a.png)

**Comment by celineaubert** [comment]
@omarbenites you can add the text about Terms of use and Privacy Policy  and  I sent you in the two areas below: 
The text can appear in a pop-up window

- [ ] in the website


![image](https://user-images.githubusercontent.com/14092820/74848735-43dc3380-5338-11ea-8185-5b59cd0829de.png)

- [ ] in the logIn page
![image](https://user-images.githubusercontent.com/14092820/74848853-5bb3b780-5338-11ea-9438-9003d4c7eb3b.png)

**Comment by celineaubert** [comment]
HI @omarbenites,
this is great the way you added the Privacy policy and terms of use in AgroFIMS.
However you did not use the last version of the text (see link in comment above). 

- [ ] Could you please change  ''Privacy notice'' to ''privacy policy'' in the titles and text?

- [ ] Could you add the link to the license: https://www.gnu.org/licenses/quick-guide-gplv3.html
![image](https://user-images.githubusercontent.com/14092820/75987795-d19b4f80-5ef0-11ea-8181-cb3f34c301f8.png)

- [ ]  Remove the unuse ''Terms of use'', change privacy notice to privacy policy, update the Copyright in the ''LogIn'' popup window 

![image](https://user-images.githubusercontent.com/14092820/75988063-4ec6c480-5ef1-11ea-86ba-9c8e101c8d2d.png)

**Comment by omarbenites** [comment]
The link has been updated with the latest changes.
