### ISSUE TITLE
Add a licence to the interface

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#247]
Add a CC licence

**Comment by omarbenites** [comment]
Poner la licencia aquí:
Link : https://github.com/AGROFIMS/hagrofims/blob/master/LICENSE

![image](https://user-images.githubusercontent.com/5264796/70272646-931db980-1776-11ea-9655-d0c73be6535d.png)

**Comment by celineaubert** [comment]
done in the policy notice
