### ISSUE TITLE
Fieldbook app compliant

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#253]

**Comment by omarbenites** [comment]
To collect information in Fieldbook App, a mobile phone application to collect data in the field, we require two files:

- Fieldbook Layout (field design)   
- Trait File (a file containing the trait definitions)

There exist certain considerations before collecting information with Fieldbook App,

- It collects one field book at time 
Example: 
[test_fb_01.xlsx](https://github.com/AGROFIMS/hagrofims/files/4155793/test_fb_01.xlsx)
[crop_measurement.txt]
- The trait files are independent of the crop classes - do not require any crop, group, subgroup attribute- and evaluation timing/period -per seasson and plot-.
Example:
(https://github.com/AGROFIMS/hagrofims/files/4155795/crop_measurement.txt)

**Comment by celineaubert** [comment]
- [x] Comment from 10/11/2020: I have tested the AgroFIMS fieldbook in Field Book and it seems that the 'variableDataType' info is at the wrong place in the trt file as it appears as the answer for the variables in the app (see pic). It seems that the ''variableDataType'' is set as a ''Default'' value in the trt file. 
![image](https://user-images.githubusercontent.com/14092820/102242272-2943fe00-3efa-11eb-91af-09401ede62a9.png)

Therefore, instead of having a calendar or a numeric pad to enter a data, the app shows as if ''date'' was the data entry for that variable. 
![image](https://user-images.githubusercontent.com/14092820/102242377-4678cc80-3efa-11eb-97c6-d08e71fa6ec4.png)

Done

**Comment by celineaubert** [comment]
- [X] In the data dictionary we listed the choice ''other'' in our lists as ''Other|.*'' to be understandable by KDSmart. Fieldbook App therefore displays .*  as a choice. Would it be possible to not include this .* in the file exported to  Fieldbook App?
- Done

**Comment by omarbenites** [comment]
The solution was to put the columns in order internally in AgroFIMS (when AgroFIMS export the fieldbook app file)

**Comment by celineaubert** [comment]
Only one AgroFIMS fieldbook at a time can be uploaded in the app. If we try to upload a second AgroFIMS fieldbook in the app the following error message pop-ups: `Unique identifiers column already contains duplicates or has already been used in a different file.`
