### ISSUE TITLE
Add warning message in Crop measurement and Phenology section if crop not chosen

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#255]
- [ ] Add a warning in Crop measurement (only if a Crop is not selected in the Crop Section)

> If the list of crop measurements is empty, verify that a crop is selected in the Crop section

![image](https://user-images.githubusercontent.com/14092820/72742825-d14a2d80-3baa-11ea-9e65-5b790a331cc4.png)

- [ ] Add a warning in Phenology (only if a Crop is not selected in the Crop Section)

> If the list of crop phenology measurements is empty, verify that a crop is selected in the Crop section
![image](https://user-images.githubusercontent.com/14092820/72743067-3a31a580-3bab-11ea-8b78-3967278328c2.png)

**Comment by celineaubert** [comment]
I don't see the warning message in the last version of AgroFIMS (v0345)
![image](https://user-images.githubusercontent.com/14092820/100329814-748b8080-2fce-11eb-84b8-69419565d7c8.png)

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
Hi @ivanperezm,

could you change the name crops section for Crop section, in the Phenology and Crop measurement page. 
![image](https://user-images.githubusercontent.com/14092820/102332143-019d7600-3f8c-11eb-82f8-b92ee527d673.png)

![image](https://user-images.githubusercontent.com/14092820/102332207-14b04600-3f8c-11eb-8685-d584ec444cfc.png)

**Comment by ivanperezm** [comment]
Done in all Tabs.
![image](https://user-images.githubusercontent.com/40466926/102742694-889f7500-4323-11eb-89c7-d4d37260c4b5.png)
![image](https://user-images.githubusercontent.com/40466926/102742720-92c17380-4323-11eb-9eeb-5d87e741348f.png)
