### ISSUE TITLE
Add Units to the variable ''Number of row''

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#256]
Hi @omarbenites could you please add a unit box  for Number of row, in Management practices>Planting, transplanting > direct seeding and transplanting? Units are listed in the Excel file: https://docs.google.com/spreadsheets/d/17k_gmu0yPMY3q25hp602_wYo4vOL-JzOONoMfqnZn-Y/edit#gid=2146395440

![image](https://user-images.githubusercontent.com/14092820/73439790-7ce44200-4350-11ea-9c49-f95857db68a9.png)

![image](https://user-images.githubusercontent.com/14092820/73439803-81a8f600-4350-11ea-8639-c5c67524b7bf.png)

(Last task remaining of the issue #222)

**Comment by omarbenites** [comment]
Fixed for the next update v.26 ✔️
