### ISSUE TITLE
Update Alliance logo

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#260]
in the ''About'page, remove CIAT and Bioversity logos, and add the Alliance logo:
![image](https://user-images.githubusercontent.com/14092820/75988518-03f97c80-5ef2-11ea-970d-01c6be669609.png)

![image](https://user-images.githubusercontent.com/14092820/75988428-dc0a1900-5ef1-11ea-8fec-2b8dcb13a67c.png)

Sorry to add it for the first release. But the logo has change since January 2020 and it would be great to update it soon.

**Comment by omarbenites** [comment]
The logo has been updated.
