### ISSUE TITLE
TraitAlias missing for ''Other crops''

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#265]
hi @omarbenites 
I noticed that the TraitAlias, the TraitValidation and the TratDataType are not exported for ''other crop'' in the Excel file. Therefore, KDSmart script does not work and we can't export fieldbook to KDSmart.
[SOXX1591706549--FInt201807_Burkina Faso.xlsx](https://github.com/AGROFIMS/hagrofims/files/4752646/SOXX1591706549--FInt201807_Burkina.Faso.xlsx)

![image](https://user-images.githubusercontent.com/14092820/84158144-d29dc900-aa6b-11ea-8d73-5d9404151964.png)

**Comment by omarbenites** [comment]
Now fixed, please check the next update.

**Comment by celineaubert** [comment]
Hi Omar, 

now there are TraitAlias, but when 2 ''other'' crops are used in the experiment, KDSMart scritp does not work, as many TraitAlias are similar (see pic and [SOXX1591706549--FInt201807_Burkina Faso (3).xlsx]). KDSmart does not accept 2 similar TraitAlias. 

Could you use the name of the crop instead of ''crop''(ex: niébé and sorghum) as you do for the TraitName
(https://github.com/AGROFIMS/hagrofims/files/4786776/SOXX1591706549--FInt201807_Burkina.Faso.3.xlsx)
?
This is the same issue for Crop Phenology measurement. they should all have different TraitAlias.
![image](https://user-images.githubusercontent.com/14092820/84777658-2a937d00-afe2-11ea-8625-7144a53430e4.png)

**Comment by omarbenites** [comment]
the link has been updated fixing this error. Please, you may check again.

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/84886581-e9a87080-b094-11ea-898f-04797b9bb0f5.png)
Great! it's working. Thanks Omar.
