### ISSUE TITLE
Depth units not exported in Excel file. 

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#266]
Depth unit is not exported in Excel files

First test:
![image](https://user-images.githubusercontent.com/14092820/85277422-b0507600-b483-11ea-803b-fb5866b2bcb8.png)

Second test:
![image](https://user-images.githubusercontent.com/14092820/85278290-0a057000-b485-11ea-9f49-5a1573283924.png)

In AgroFIMS, unit are selected
![image](https://user-images.githubusercontent.com/14092820/85278352-230e2100-b485-11ea-839c-f5cd9a0aa7da.png)
[TETE1589981230--FMCassava202005_Afghanistan (2).xlsx](https://github.com/AGROFIMS/hagrofims/files/4812695/TETE1589981230--FMCassava202005_Afghanistan.2.xlsx)

**Comment by omarbenites** [comment]
Fixed in the next update.

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/85408269-963a9480-b564-11ea-99e4-e4d08173e28b.png)
 thanks, it's working fine!
