### ISSUE TITLE
Add help icons

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#281]
Hi @ivanperezm ,
Please find the interface screen shots with help icons and links to help documentation. You may have a better idea for the help icon, color and position. 
Let me know if you need more details

[Help page.docx](https://github.com/AGROFIMS/hagrofims/files/5667143/Help.page.docx)

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
Hi @ivanperezm,

thanks for adding the icon and links.

- [ ] There is an icon missing next to the profile to redirect user to the Help website: https://agrofims.github.io/helpdocs/

![image](https://user-images.githubusercontent.com/14092820/102333455-be440700-3f8d-11eb-8d61-716646b24192.png)

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/102742576-32cacd00-4323-11eb-92d7-4346d1bda38b.png)
