### ISSUE TITLE
Text to add in the Documentation page of AgroFIMS

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#283]
**General guidance to help you use AgroFIMS**

1. Set up your experimental site (in “Sites”).
2. Add a new experiment (in “Experiments”).
3. Then specify what the experiment is about, and indicated the personnel, organizations, and funding agencies involved (in ''Experiment'' and “Personnel” tabs). This is the metadata about the dataset.
4. Add a fieldbook (in “Fieldbooks” tab), choosing the country and experimental site you created earlier.
5. Add details on the site, crop, and statistical design of the experiment, choosing treatments and factors from the drop-down lists.
6. Go through the “Management practices” to specify how you want the experiment to be managed.
7. Specify crop, phenological, weather, and soil measurements that you would like to make.
8. Once you are done, you can download the fieldbook you have created via the cloud icon at the top right.
The fieldbook file can be downloaded as an Excel file or as a KDSmart or Field Book compatible files for digital data collection. KDSmart and Field Book are available for Android devices. S
Once data is collected via KDSmart, you can send it back to AgroFIMS for statistical analysis. This module will soone be available and includes a statistical report with graphs.

For further guidance, please visit the following websites:

**User manual**
An online version of the user manual can be found here: https://agrofims.github.io/helpdocs/ 
A PDF of this user manual is also available here. _(link to be added)_

**AgrAPI**
We have made available the Agronomy API or AgrAPI, which is a RESTful web service API specification to enable access, exchange, and integration of agronomic data across systems and applications. You can use the API to retrieve research management information, experimental designs, crop measurements, and environmental variables from AgroFIMS. The AgrAPI blueprint can be implemented in different programming languages. Currently, AgrAPI is implemented in the R statistical programming language allowing you to analyze your data with the R statistical packages and graphics of your choice.
https://con.agrofims.org/agrofims/report/api.html

**Interface development**
The development history of AgroFIMS, with the different development versions of the interface is available here: https://con.agrofims.org/agrofims/report/documentation.html

**Comment by ivanperezm** [comment]
Done!

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/102742527-19c21c00-4323-11eb-9171-da2f4db3a039.png)

**Comment by ivanperezm** [comment]
Last update, done!

![image](https://user-images.githubusercontent.com/40466926/102814493-bb378500-4398-11eb-90ec-ace7e1e69f27.png)

**Comment by celineaubert** [comment]
Hi Ivan,

the URL for the PDF has been published today. Could you please add it in the text as a hyperlink in Documentation? https://hdl.handle.net/10568/110884
![image](https://user-images.githubusercontent.com/14092820/104911292-ed81d580-598a-11eb-954f-4a292d02016f.png)

Thanks!

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/105082922-3e183200-5a62-11eb-9d9d-e65b0dc8b02f.png)
