### ISSUE TITLE
Allow to select ''Other'' more than once in management practices

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#284]
In the tab management practices, users should be able to select the choice ''other'' more than once, since they may have multiple ''other'' management practices to list. 

![image](https://user-images.githubusercontent.com/14092820/102244458-9eb0ce00-3efc-11eb-9806-ab194cf8a9f2.png)

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
done in v 039
![image](https://user-images.githubusercontent.com/14092820/102347243-6d89d980-3fa0-11eb-839a-18640733ad3f.png)
