### ISSUE TITLE
Fertilizer and Nutrient factor - add the title : ''Nutrient content in product (%)''

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#285]
In the Design tab, add the title : ''Nutrient content in product (%)'' at the top of the nutrient table in the pop-up window for the Fertilizer amount and Nutrient amount factors.

![image](https://user-images.githubusercontent.com/14092820/102245578-0582b700-3efe-11eb-896a-60279e9a4371.png)

![image](https://user-images.githubusercontent.com/14092820/102245686-264b0c80-3efe-11eb-97e6-8e505fcfff4d.png)

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
![image](https://user-images.githubusercontent.com/14092820/102330900-69eb5800-3f8a-11eb-8d9b-3b32cd4dd9b9.png)
done in v.0369
