### ISSUE TITLE
Update management practices text

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#286]
Hi @ivanperezm could you please update the text in the management practices tab to the one below:

Choose management practices relevant to your experiment from the list below. Then choose more specific practices. 

If you want to create a protocol to give your field managers guidelines on how the experiment should be managed, assign values to the practices and slide the **Planned protocol** button.  

If you wish to get information about actual management in the field (i.e., unanticipated changes in planned protocol), or for a management practice involving decisions made in the field, select it and slide the **Actual management** button. The management practice will then be listed as a measurement to be made in the field, allowing you to get its actual value.   

![image](https://user-images.githubusercontent.com/14092820/102347349-97db9700-3fa0-11eb-94a4-a182e81d17c0.png)

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/102742450-e97a7d80-4322-11eb-9e44-68e4971ef6d0.png)
