### ISSUE TITLE
Area harvested should be depicted as number or rows x length harvested and as length x width

### ISSUE THREAD

**Issue by mdevare** [AGROFIMS/hagrofims#29]
Area harvested to be depicted as: 'number of rows x length harvested' and 'length x width harvested' which gives a calculated value for area harvested

**Comment by celineaubert** [comment]
we changed rows in the dictionary. For harvest the ''Row'' variables need to all appear when ''row'' is selected - To be explained to the CIP team

**Comment by celineaubert** [comment]
done in v22
