### ISSUE TITLE
Add as many text boxes or list boxes as the number of level (in Design--> Factor)

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#43]
Design→ Factor →add as many text box or list box as the number of level selected by the user. (see picture below)
![factor](https://user-images.githubusercontent.com/14092820/45740621-f49b4c00-bbf5-11e8-9f14-e14396182046.PNG)

**Comment by marieALaporte** [comment]
can close then?

**Comment by celineaubert** [comment]
not relevant anymore with the new design of the factor module
