### ISSUE TITLE
Have a protocol tab in the Excel file

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#50]
Have a protocol tab (named Protocol) in the exported fieldbook with all the information about the experiment conditions (growing season condition) and the list of measurements (crop, soil, weather, phenology) with the dates they have to be measured (fill in by PI in AgroFIMS)

**Comment by celineaubert** [comment]
The information filled in AgroFIMS go into the protocol tab in the Excel file:

![image](https://user-images.githubusercontent.com/14092820/56120151-e0da7d00-5f6d-11e9-8e3f-79e7b574ae23.png)

![image](https://user-images.githubusercontent.com/14092820/56120191-f2bc2000-5f6d-11e9-8293-70e852e1d75a.png)

**Comment by celineaubert** [comment]
Other example
![image](https://user-images.githubusercontent.com/14092820/56121908-7b888b00-5f71-11e9-87c9-6e42a4c36c80.png)

**Comment by celineaubert** [comment]
List of info added in AgroFIMS and not exported in the protocol tab (test done with the test-v24 on 6th August) [fileNameBook (7).xlsx](https://github.com/AGROFIMS/hagrofims/files/3471439/fileNameBook.7.xlsx)


- [ ]  land levelling traction type

- [ ] puddling info are not exported

- [ ]  tillage info are exported twice

- [ ] Seeding traction type, seeding rate, distance between plant, number of rows
![image](https://user-images.githubusercontent.com/14092820/62527808-27652780-b83c-11e9-9905-48236b6ae884.png)

- [ ]  Transplanting: distance between rows, number of rows

![image](https://user-images.githubusercontent.com/14092820/62528234-cd189680-b83c-11e9-9540-c91937ff6fb8.png)

- [ ]  Much traction type, percentage of coverage

![image](https://user-images.githubusercontent.com/14092820/62528382-0d781480-b83d-11e9-830b-8f50b733acb5.png)

**Comment by omarbenites** [comment]
Fixed for the next version!
