### ISSUE TITLE
Leave the date boxes blank in the Excel file

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#51]
If a date is pre-filled in the Excel fieldbook, maybe the data collector would collect data in another day an not change the date. Then the record is incorrect. It would be better to let the date blank in the Excel. The planned date will be recorded in the protocol tab.

**Comment by marieALaporte** [comment]
@celineaubert with KDSmart we agreed that this is ok for the date to appear if the date if pre-filled. Close if not needed anymore
