### ISSUE TITLE
Add the possibility to link weather measurement to weather station or sensor

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#52]
In weather measurement, users could choose manual measurement or weather station.
If manual is chosen, the current list of variables appears.
If station is chosen, the current list of variables appears with the possibily to add measurement dates and weather station location.

**Comment by vhualla** [comment]
We attached the information of weather for both options and graphics 
[Weather.pdf](https://github.com/AGROFIMS/hagrofims/files/2452174/Weather.pdf)
[Weather.xlsx](https://github.com/AGROFIMS/hagrofims/files/2452175/Weather.xlsx)

**Comment by celineaubert** [comment]
I did some edits on the Excel file using using ''Track changes''. 
[Weather.xlsx](https://github.com/AGROFIMS/hagrofims/files/2456070/Weather.xlsx)

It will be great to discuss the variable list during our next meeting

**Comment by marieALaporte** [comment]
I think this can be closed. @celineaubert ?
