### ISSUE TITLE
Add strip plot and split plot as experimental design

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#57]
Add strip plot, Split plot in experimental design in Design Information

**Comment by celineaubert** [comment]
E.g. split plot, strip plot, latin square. Medha to provide field experiment templates (from Sarah - IRRI; Pieter - IITA; Peter - CIMMYT; Bally - CIMMYT

**Comment by omarbenites** [comment]
Those designs are already included.
