### ISSUE TITLE
Implement GeoHash

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#7]
Current issue: When a site is created (e.g. CIP station), the ID for this same site can be different, based on the geolocations, which are likely to be different. i.e., 2 researchers may have the same site name, with different geolocations. Or 2 researchers could set up trials on the same plots (same geolocations) one after another (say, trial 1 runs for 5 years, then another researcher runs trial 2 on the same site, same plots). Implement GEOhash (http://geohash.org/)

**Comment by frostbytten** [comment]
https://cran.r-project.org/web/packages/geohash/vignettes/geohash.html

**Comment by celineaubert** [comment]
What is important for analysis is the geo-localisation of a site. The name is not so important. Therefore, it does not matter if a same location have different names, or if similar names are used for different location. 
For a query the lat/long will be used, not the site name.
