### ISSUE TITLE
Add soil fertility data to exported field book

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#70]
Soil fertility logic/ordering in AgroFIMS (or app): 
- How much N,P,K do you want to add? 
- What do your splits look like? (number of applications, how much N,P,K per application, which fertilizer formulations for each application)
- Show a table with the N,P,K,... elemental content of each formulation selected by the user. Allow the user to change the content (e.g. if formulation tested)
- AgroFIMS/app then tells you the quantity of each product to add to deliver desired NPK rates

_(WS September)_

**Comment by celineaubert** [comment]
**Soil fertility mock-up**
I did not find a solution for the case where
- more than one fertilizer is applied at once.
- more than one nutrient content is intended to be applied at once

![soil fertiliy - mock-up](https://user-images.githubusercontent.com/14092820/49530198-0963b380-f8b8-11e8-9143-12fa5f1a6eda.jpg)

**Comment by celineaubert** [comment]
Product field says “select one” but permits entry of multiple values
![image](https://user-images.githubusercontent.com/14092820/54540752-d5a92700-4998-11e9-912d-88aaaa2cb069.png)

_(WS March)_

**Comment by celineaubert** [comment]
An element rate (kg/ha) that exceeds the overall product rate is not flagged as an error.

_(WS March)_

**Comment by celineaubert** [comment]
Pieter uses an algorithm in R (limSolve) to calculate the fertilizer rate base on the nutrient rate you want to apply (Pieter shared the Package with Raul)

**Comment by celineaubert** [comment]
Need to be able to replicate fertilizer application data and change only what is different.

_(WS March, Cheryl)_

**Comment by celineaubert** [comment]
Broadcast incorporated – implies a soil depth. Should have option to enter depth.

_(WS March, Cheryl)_

**Comment by celineaubert** [comment]
- [ ] Medha and Robert will look at the R package of Pieter and build a mock-up based on it.

- [ ] build it as a pop-up (plugin/external tool) or a new tab (Omar and Ivan could think how to implement it)

**Comment by celineaubert** [comment]
Hi @omarbenites and @ivanperezm , this is a mock-up for the [Soil fertility module in management practices.docx](https://github.com/AGROFIMS/hagrofims/files/3382022/Soil.fertility.module.in.management.practices.docx)

We must add, for each split application: 
-	Application technique
-	Timing
-	Implement type

**Comment by omarbenites** [comment]
Mockup for Design+Soil Fertility module

[Improvement_AGROFIMS-02-07-2019.pptx](https://github.com/AGROFIMS/hagrofims/files/3382656/Improvement_AGROFIMS-02-07-2019.pptx)

**Comment by celineaubert** [comment]
Hi @omarbenites and @ivanperezm , this is an updated mock-up for the 
[Soil fertility module in Design](https://github.com/AGROFIMS/hagrofims/files/3427310/Design-.Fertilizer.factor.docx)

**Comment by omarbenites** [comment]
Hi Celine, @celineaubert, here some questions about Soil Fertility module:

1.  Will `Timinig` combo box (picture below) work similar to the Timing combo in Crop Measurement/Weather/Soil?  
![image](https://user-images.githubusercontent.com/5264796/62662208-eb63bc80-b938-11e9-8a9d-cc1a66fec05a.png)

2. What are the combo's values for technique?
![image](https://user-images.githubusercontent.com/5264796/62662258-1d751e80-b939-11e9-9d92-6d65405e2961.png)

3. Same for `Implement`
![image](https://user-images.githubusercontent.com/5264796/62662680-7a250900-b93a-11e9-9d07-86715ece46c5.png)

**Comment by celineaubert** [comment]
Hi @omarbenites ,

1- yes, this combo box will work like the one for crop measurements
2- Listed in the data dictionary, in Fertilizer management, lines 122 to 135
3- Listed in the data dictionary, in Fertilizer management, lines 136 to 145

**Comment by celineaubert** [comment]
**Soil fertility module spec**

•	List of fertilizers 
•	Pre-filled and editable nutrients' content table
•	Number of split applications
•	Select product/ nutrient per split
•	Box for nutrient/product rate
•	Application timing per split
•	Application technique per split
•	Implement type per split
•	Able to calculate the amount of product to add per plot (based on the plot’s dimension)

•	AgroFIMS calculate nutrient rate or product rate
•	Box for product/ nutrient rate calculated by AgroFIMS

**Comment by celineaubert** [comment]
- [ ] Change level for ‘’ add nutrient’’, and ‘’add fertilizer’’
![image](https://user-images.githubusercontent.com/14092820/63534871-6e2b7080-c510-11e9-8d46-30211eae11bd.png)
![image](https://user-images.githubusercontent.com/14092820/63534880-72f02480-c510-11e9-9fd2-d13eb6c21671.png)

- [ ] -	Change type for ‘’ nutrient’’ or ‘’ fertilizer’’
![image](https://user-images.githubusercontent.com/14092820/63534922-8602f480-c510-11e9-9135-ce8037d6c533.png)

- [ ] Update nutrient table (4 new nutrients in the ''Fertilizer-nutrients content'' excel file in Drive)

- [ ] -	Rearrange the boxes to gain space in the pop-up box (align the fertilizer name below fertilizer title, remove 1, Remove name of fertilizer, add space between nutrient content table and timing, Frequency boxes, reduce Technique box)
![image](https://user-images.githubusercontent.com/14092820/63535410-a8e1d880-c511-11e9-8a7a-44f8021ec8b1.png)
![image](https://user-images.githubusercontent.com/14092820/63535627-3291a600-c512-11e9-8c35-36e2da1419aa.png)

- [ ] possibility to add more than one ''date'' for timing

- [ ] Keep Technique, implement and timing when I click ''refresh''

**Comment by celineaubert** [comment]
- [ ] Add ''add split'' feature
![image](https://user-images.githubusercontent.com/14092820/63536950-f6ac1000-c514-11e9-92f7-72971189c155.png)

**Comment by omarbenites** [comment]
Hi @celineaubert , here I attach the final version of the mockup for **Nutrient type and amount**
[Nutrient_Type_Amount.docx](https://github.com/AGROFIMS/hagrofims/files/3576154/Nutrient_Type_Amount.docx)

Analogously, for the **Fertilizer type and amount**

**Comment by celineaubert** [comment]
Hi Omar,
this looks good to me!
Céline AubertEmail: aubertceline@ymail.comPhone: +33 (0)6.95.87.20.30                                                                                  

 

    Le mercredi 4 septembre 2019 à 21:28:05 UTC+2, Omar Eduardo Benites Alfaro <notifications@github.com> a écrit :  
 
 
Hi @celineaubert , here I attach the final version of the mockup for Nutrient type and amount
Nutrient_Type_Amount.docx

Analogously, for the Fertilizer type and amount

**Comment by omarbenites** [comment]
Latest enhancements:

- Approximate to 1 decimal all product/fertilizer values
- Remove index of rows
- Number of `splits` instead of `Split` 
-Remove `frequency` from Timing

**Comment by omarbenites** [comment]
- [ ] Probar cambiando `rhandsontable` por DT library
- [ ] Cuando un nutrient es cero la caja de seleccion de Product (`select product`) debe bloquearse o quedar como no seleccionable. Ademas, internamente debe aparecer como una matriz de puros ceros.
![image](https://user-images.githubusercontent.com/5264796/64896775-9a856900-d646-11e9-86b1-fa0171e880fe.png)
- [ ] Chequear la rutina para colectar los datos de los nutrientes.
- [ ] Chequear como calcular los `calculations`

**Comment by celineaubert** [comment]
@omarbenites - comments on the interface
![image](https://user-images.githubusercontent.com/14092820/65616201-f3e08700-dfba-11e9-86ca-918a3cf96d9d.png)

**Comment by celineaubert** [comment]
@omarbenites here are an example how the info about fertilizer filled in Design and Management practices should appear in the Excel file [fertilizer variables in Excel file.xlsx](https://github.com/AGROFIMS/hagrofims/files/3653494/fertilizer.variables.in.Excel.file.xlsx)

**Comment by celineaubert** [comment]
@omarbenites 

- [ ] When nutrient is selected in Mngt Practices
The calculation is wrong. It calculates the nutrient amount and not the Product amount. In my example, the product amount calculated should be 434,7kg/ha
![image](https://user-images.githubusercontent.com/14092820/66114001-382ce200-e5ce-11e9-8a08-b4131c383e85.png)

**Comment by omarbenites** [comment]
- Export the nutrient and fertilizer data from Design in the exported fieldbook

**Comment by celineaubert** [comment]
Hi @omarbenites 

I have exported a fieldbook with fertilizer info in the protocol.
![image](https://user-images.githubusercontent.com/14092820/69171055-7b4e0080-0afb-11ea-90cd-63d6595cc2f7.png)
There is no information that those lines are about fertilizer application, and which one (if more than one application). 

It does not look like what I have suggested on Sep 25 (see comment above)
![image](https://user-images.githubusercontent.com/14092820/69171191-c6681380-0afb-11ea-8659-de774a4505e5.png)

Could you please clarify your choice?

**Comment by celineaubert** [comment]
Hi @omarbenites , what do you think of the below TraitName? Also, those names have to also be written in the column ''Group'' (if not, KDSmart script does not work):

Fertilizer_name
Fertilizer_nutrientcontent
Fertilizer_amount
Fertilizer_timing
Fertilizer_technique
Fertilizer_traction
Fertilizer_nutrientadded
 
**If more than one split**
Fertilizer_name_split2
Fertilizer_nutrientcontent_split2
Fertilizer_product_amount_split2
Fertilizer_timing_split2
Fertilizer_technique_split2
Fertilizer_traction_split2
Fertilizer_nutrientadded_split2





**Nutrient**
![image](https://user-images.githubusercontent.com/14092820/73961030-29539480-490c-11ea-9432-adb350acbba4.png)

**Product**
![image](https://user-images.githubusercontent.com/14092820/73961322-a67f0980-490c-11ea-838c-d5f27d5648ea.png)

**Comment by omarbenites** [comment]
The next labels has been added:

- [x] Fertilizer_timing_
- [x] Fertilizer_technique_
- [x] Fertilizer_traction_
- [x] Fertilizer_nutrientadded_split

**Comment by celineaubert** [comment]
@omarbenites could you please add the following labels:

- [ ] Fertilizer_name
- [ ] Fertilizer_amount
- [ ] Fertilizer_nutrientcontent

With the info currently exported into the Excel file, the person in the field has no information on the name of the fertilizer and the quantity to use.

Also, in the tab ''Protocol'' of the Excel file, KDSmart concatenates the info from Group_Subgroup_Measurement to create a name. So if the names in Subgroup and Measurement are the same for all the lines of fertilizer, the script does not work because it thinks the lines are the same (this is the case now).
![image](https://user-images.githubusercontent.com/14092820/74232510-3e904080-4cc9-11ea-814b-049f1428dd88.png)

A way to change that is either to put the same Name as TraitName in the column Group
![image](https://user-images.githubusercontent.com/14092820/74232618-76978380-4cc9-11ea-8de3-2ff06972ea4d.png)


or to to put ''Fertilizer'' in Subgroup, and the TraitName in Measurement
![image](https://user-images.githubusercontent.com/14092820/74232728-b0688a00-4cc9-11ea-9010-db516b39f85d.png)

**Comment by celineaubert** [comment]
Hi @omarbenites,
The current set up of the Fertilizer info in the Excel file works when Prodcuct is selected in Mngt Practices. 
![image](https://user-images.githubusercontent.com/14092820/85410730-bb7cd200-b567-11ea-8090-06ebed84cce8.png)


However, when Nutrient is selected, there is no info on the fertilizer product and the fertilizer amount. 

-->Info typed in AgroFIMS, in Mngt Practices, fertilizer, Nutrient:

![image](https://user-images.githubusercontent.com/14092820/85408541-f29db400-b564-11ea-8338-50305bcacdba.png)

--> Info in Excel file:
![image](https://user-images.githubusercontent.com/14092820/85408488-e0237a80-b564-11ea-972c-e4d054d2522c.png)

The info ''Fertilizer_nutrientadded  S_250'' in the Excel file is wrong. I did not add 250kg/ha of S, I have added 250kg/ha of Sulfur-coated urea. 

--> The info in Excel files should be like this:
![image](https://user-images.githubusercontent.com/14092820/85409182-ca628500-b565-11ea-81ce-e1186ec0e6bb.png)

- [ ] @omarbenites could you please add : Fertilizer_product and Fertilizer_amount in the Excel file when Nutrient is selected in Mngt practices

- [ ] Could you remove ''_split1'' when there is only 1 split

- [ ] Could Fertilizer_amount (or Fertilizer_product) be listed on the top of the list of fertilizer info in the tab Protocol

- [ ] Could you list all the Fertilizer info of one split together in the protocol tab:
![image](https://user-images.githubusercontent.com/14092820/85411280-6bead600-b568-11ea-939e-b989e2436694.png)

**Comment by celineaubert** [comment]
see issue #274
