### ISSUE TITLE
Adapt AgroFIMS for long-term experiments - across seasons, particularly for rotation experiments

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#76]
Long-term experiment: the design might change over the years, but the core data are usable over the years because most of the design stays the same. i.e., multiple FB ids linked to one experiment id.

**Comment by celineaubert** [comment]
Indicate that an experiment is a continuation of a previous year?

**Comment by marieALaporte** [comment]
linked to both the rotation module and having the ExpID/Fieldbook

**Comment by celineaubert** [comment]
With the fact that more than one fieldbook can be created under a same experiment, this could be sufficient for adaptating long term experiment.
