### ISSUE TITLE
Indicate mandatory fields by adding an asterix

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#83]
- [ ] Select the mandatory information

- [ ] Add a sign to highlight the mandatory fields (ex: a red start)

**Comment by celineaubert** [comment]
check with the CGcore Metadata schema

**Comment by celineaubert** [comment]
Allow users to choose the mandatory fields (comment from Abhi)

**Comment by celineaubert** [comment]
Mandatory fields: 

- [x] Experiment name

- [x] Cropping system

- [x]  crop name 
@ivanperezm could you add a star next to cropping system and crop name to highlight that there are a mandatory fields?
![image](https://user-images.githubusercontent.com/14092820/99285216-8e430000-2837-11eb-92c4-a670da0138da.png)

**Comment by celineaubert** [comment]
Thanks @ivanperezm for adding a star to the Crop name. Could you add a star to the following fields (and to any mandatory filed I may I forgot to list)?:

**Site**

- [x] Country name

- [x] Site

**Crop**

- [x] Cropping system

- [x] Crop name

**Design**

- [x] Experimental design

- [ ] Factor

- [x] **Crop measurements**

**Comment by ivanperezm** [comment]
Done in all cases.
![image](https://user-images.githubusercontent.com/40466926/102742974-580c0b00-4324-11eb-9b40-cb48e0e63c65.png)

**Comment by celineaubert** [comment]
@ivanperezm ,  1 asterix is missing for Factor. Maybe you can add it next to Treatment description
![image](https://user-images.githubusercontent.com/14092820/102766220-17d97680-437e-11eb-95fd-e530a5daea67.png)

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/102815494-6d238100-439a-11eb-813c-39e0ec128c12.png)
![image](https://user-images.githubusercontent.com/40466926/102815555-80cee780-439a-11eb-8e99-a1b2cf1bf7ae.png)
