### ISSUE TITLE
Redesign Funding agency and project management entity module

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#90]
The module on the funding agencies and the project management entities could be in two separate modules. The design could change a little as proposed below: 
1. A title
2. Ask the type and then the name
3. A button ''Add'' below to add more organizations

- Grant number and title need to be added.

Find below the curent page and a mockup of the proposed changes.

Current page: ![image](https://user-images.githubusercontent.com/14092820/46672558-0c079c80-cbd8-11e8-9f7c-b50d93552bbb.png)

Proposed page: 

![image](https://user-images.githubusercontent.com/14092820/46737546-125f4c80-cc9c-11e8-89d7-e9ab5121bdac.png)

**Comment by celineaubert** [comment]
clarify what a “mgmt entity” is (grantee) and what an “expt lead” is (sub-grantee)

**Comment by marieALaporte** [comment]
fixed in v22
