### ISSUE TITLE
Add more intercrop patterns

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#92]
Intercrop in not alway in row: need to have pattern of intercrop:
 - in the same hole
- within rows
- in between rows
- subsitutives rows
- ...

**Comment by celineaubert** [comment]
I have review the list of copping system and edited the list in AgroFIMS. 
Patterns added to AgroFIMS:

- Within-row intercropping : where the component crops are planted simultaneously within the same row in varying seeding ratios
- Strip intercropping. "Growing two or more crops simultaneously in different strips wide enough to permit independent cultivation but narrow enough for the crops to interact agronomically." 
- Temporal intercropping: practices of sowing a fast-growing crop with a slow-growing crop, so that the first crop is harvested before the second crop starts to mature.

Sources:
https://en.wikipedia.org/wiki/Intercropping
https://www.researchgate.net/publication/224934832_Annual_intercrops_An_alternative_pathway_for_sustainable_agriculture#pf4
https://eap.mcgill.ca/CSI_1.htm

**Comment by celineaubert** [comment]
@omarbenites Could you add the new choices in AgroFIMS (see Crop tab : https://docs.google.com/spreadsheets/d/1whG77uKTYb6TJtLFIK7GkmH8Nk3haoFAtUvg78F3jKU/edit#gid=1840942945). 

You can remove the box for ''Intercrop details'' , as the choices ''mixed intercropping'' and '' row intercropping'' have been added to the combo box: Cropping system
![image](https://user-images.githubusercontent.com/14092820/99985090-2730c880-2dae-11eb-9231-f0cefea8f39d.png).

**Comment by omarbenites** [comment]
Hi Celine, we would not be able to do this. This combo, is a key component in the database, Interface and download.
This is an issue from 2018, maybe we can discuss more about this issues or close the very older ones from 2 years ago. Additionally, the migration is also based on the Shiny version.

**Comment by celineaubert** [comment]
An easier way to close this issue, would be to keep the choice for ''Cropping system'' as monocrop, intercrop, relay crop.

And for ''Intercropping details'' have the choices: Mixed intercropping|Row intercropping|Strip intercropping|Within-row intercropping.

If mixed intercropping or strip intercroppping is chosen, the box ''row geometry'' appears.

**Comment by ivanperezm** [comment]
Done!

**Comment by celineaubert** [comment]
Hi @ivanperezm , 
I am sorry, I did a mistake in my comment. The box ''row geometry'' should appear if Row intercropping and strip intercropping are selected (not mixed intercropping).
I apologize.

**Comment by ivanperezm** [comment]
Done!
![image](https://user-images.githubusercontent.com/40466926/102742908-23984f00-4324-11eb-9d21-012fdcc379a2.png)
![image](https://user-images.githubusercontent.com/40466926/102742923-2dba4d80-4324-11eb-8b19-a2d02371e6ed.png)
