### ISSUE TITLE
Experimental conditions modules organized in the order of the experiment

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#96]
instead of having the modules ordered alphabetically, they should come in the order of the experiment 
1. mulching and residue
2. land preparation
3. Soil fertility
4. Planting and transplanting
5. Irrigation
6. Weeding
7. Harvest
![image](https://user-images.githubusercontent.com/14092820/46677606-4296e480-cbe3-11e8-9ba4-6797d1da8b9f.png)

![image](https://user-images.githubusercontent.com/14092820/46677844-a28d8b00-cbe3-11e8-88ad-2398380b70f4.png)

**Comment by marieALaporte** [comment]
fixed in v22
